# Imports and data:

In [1]:
import pandas as pd
import numpy as np
import regex as re

In [2]:
w1 = pd.read_excel("data/WINNERS 2000-2010 - 05.xlsx")
w2 = pd.read_excel("data/WINNERS 2011-2020 - 05.xlsx")
w3 = pd.read_excel("data/WINNERS 2021-2025 - 05.xlsx")
w4 = pd.read_excel("data/WINNERS 2026-2030 - 05.xlsx")

In [3]:
winners = pd.concat([w1, w2, w3, w4], ignore_index=True)

winners.shape

(43457, 10)

In [4]:
winners.dtypes

Name                   object
School                 object
Year                    int64
City                   object
Award                  object
Division               object
Category               object
School / Company       object
Division / Position    object
Dance Category         object
dtype: object

In [5]:
winners

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
0,NaN,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
1,NaN,"The Kirov Academy, DC",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
2,8+3,Inwood Dance Company,2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
3,Cabaret,"Dance Conservatory, DE",2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
4,Make Them Hear You,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",2nd Place,NaN,Ensembles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
43452,Dance For Six,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43453,Coppelia Friends Dance,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43454,Kira Fargas,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43455,Hadassah Perry,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43456,NaN,NaN,2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

In [6]:
# for s in winners.School.value_counts().index:
#     print(s)

In [7]:
# for a in winners["Award"].value_counts().index:
#     print(a)

In [8]:
winners["Division"].value_counts()

Division
Senior Age Division             2837
Junior Age Division             2604
Pre-Competitive Age Division    1102
Top 12 - Senior Age Division       1
Name: count, dtype: int64

In [9]:
winners["Category"].value_counts()

Category
Classical Dance Category                   2909
Contemporary Dance Category                2874
Ensembles                                   451
Special Awards                              446
Large Ensembles                             133
Pas De Deux                                  73
Small Ensembles                              67
Classical & Contemporary Dance Category      24
Duets & Trios                                 3
Name: count, dtype: int64

In [10]:
# for i in winners["Division / Position"].value_counts().index:
#     print(i)

In [11]:
winners["Division / Position"] = winners["Division / Position"].str.replace(r"\(.*\)", "", regex=True).str.strip()
winners["Division / Position"].value_counts()

Division / Position
Junior Age Division             11795
Senior Age Division             11604
Pre-Competitive Age Division     7446
Large Ensembles                   368
Small Ensembles                   358
Pas De Deux                       293
Ensembles                         130
Special Awards                    120
Duet/Trio                          16
Name: count, dtype: int64

In [12]:
winners[winners.Name.str.contains(",", na=False)][["Name", "Category", "Division / Position"]]

,Name,Category,Division / Position
6,"Kory Glatman, NJ",NaN,NaN
87,"Melissa Lorry, MA",Contemporary Dance Category,NaN
124,"Arizona Ballet School, AZ",Special Awards,NaN
186,"April Rae, MD",NaN,NaN
207,"Bills, Bills, Bills",Large Ensembles,NaN
...,...,...,...
41363,"Strong, Calm, Slow",NaN,Duet/Trio
41910,"Diana & Acteon , Pas De Deux",NaN,Small Ensembles
41912,"Diana & Acteon , Pas De Deux",NaN,Small Ensembles
43165,"Spin, Measure, Cut",NaN,Small Ensembles
43180,"Spin, Measure, Cut",NaN,Small Ensembles

In [13]:
winners.loc[
    winners["Dance Category"].str.contains("Ensembles And Pas De Deux", na=False), 
    "Dance Category" 
] = "Ensembles & Pas De Deux"

winners.loc[
    winners["Dance Category"].str.contains(r"\bDuet\b|\bTrio\b", na=False), 
    "Dance Category"
] = "Duet/Trio"

In [14]:
winners["Dance Category"].value_counts()

Dance Category
Classical Dance Category                   17361
Contemporary Dance Category                11612
Ensembles                                   1793
Special Awards                               889
Pas De Deux                                  477
Large Ensembles                              198
Small Ensembles                              110
Classical & Contemporary Dance Category      104
Ensembles & Pas De Deux                       47
Duets & Pas De Deux                           28
Contemporary/Open Dance Category              17
Top 12                                        15
Duet/Trio                                     11
Traditional Dance Category                     9
Top 6                                          6
Name: count, dtype: int64

In [15]:
winners.isna().sum()

Name                     554
School                 36132
Year                       0
City                       0
Award                    174
Division               36913
Category               36477
School / Company        8286
Division / Position    11327
Dance Category         10780
dtype: int64

- Some awards are for the school overall rather than a person
- Some awards are for the name of the dance rather than people
- School awards wouldn't have a Dance Category or Position, which would explain some entries being null
- NaNs in certain columns can actually tell you what kind of award is being given:
    - NaN in School/Company ; School Award
- Some people don't belong in a School/Company

# Data Cleanup:

- Whenever Name and School have NaNs, there are no rows where School/Company is empty
    - So: replace School with whatever is in the School/Company for that row

In [16]:
winners[
    (winners.Name.isna()) & 
    (winners.School.isna())
]

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
7717,NaN,NaN,2011,"Torrington, CT",Outstanding School Award,NaN,NaN,"Washington School of Ballet, DC, USA",NaN,Special Awards
7806,NaN,NaN,2011,"Tampa, FL",Outstanding School Award,NaN,NaN,The Art of Classical Ballet,NaN,Special Awards
7807,NaN,NaN,2011,"Tampa, FL",Outstanding School Award,NaN,NaN,America's Ballet School,NaN,Special Awards
7905,NaN,NaN,2011,"San Francisco, CA",Outstanding School Award,NaN,NaN,"Los Angeles Ballet Academy, CA",NaN,Special Awards
7906,NaN,NaN,2011,"San Francisco, CA",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",NaN,Special Awards
...,...,...,...,...,...,...,...,...,...,...
42644,NaN,NaN,2026,"Boca Raton, FL",Outstanding School Award,NaN,NaN,"Stars Dance Studio, FL",Special Awards,NaN
42928,NaN,NaN,2026,"Indianapolis, IN",Outstanding School Award,NaN,NaN,"Indiana Ballet Conservatory, IN",Special Awards,NaN
43200,NaN,NaN,2026,"Boston-Worcester, MA",Outstanding School Award,NaN,NaN,"N&D Ballet, MA",Special Awards,NaN
43201,NaN,NaN,2026,"Boston-Worcester, MA",Outstanding School Award,NaN,NaN,"Koltun Ballet Boston, MA",Special Awards,NaN
43456,NaN,NaN,2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

In [17]:
winners[
    (winners.Name.isna()) & 
    (winners.School.isna()) &
    (winners["School / Company"].isna())
]

Empty DataFrame
Columns: [Name, School, Year, City, Award, Division, Category, School / Company, Division / Position, Dance Category]
Index: []

In [18]:
mask = (winners["Name"].isna()) & (winners["School"].isna())

winners.loc[mask, "School"] = winners.loc[mask, "School / Company"]
winners

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
0,NaN,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
1,NaN,"The Kirov Academy, DC",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
2,8+3,Inwood Dance Company,2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
3,Cabaret,"Dance Conservatory, DE",2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
4,Make Them Hear You,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",2nd Place,NaN,Ensembles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
43452,Dance For Six,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43453,Coppelia Friends Dance,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43454,Kira Fargas,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43455,Hadassah Perry,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43456,NaN,"Westlake School for the Performing Arts, CA",2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

In [19]:
mask =  (winners.School.isna()) & (~winners["School / Company"].isna())
winners.loc[
    mask,
    "School"    
] = winners.loc[mask, "School / Company"]

- Removing hanging whitespace from all string columns since it will effect analysis
- Turn everything uppercase, since there are inconsistent capitalization (or lack thereof)

In [20]:
winners["Name"] = winners.Name.str.strip()

In [21]:
str_cols = winners.select_dtypes(include=["object", "string"]).columns

for col in str_cols:
    mask = winners[col].notna()
    winners.loc[mask, col] = (
        winners.loc[mask, col]
        .astype(str)
        .str.replace(r"\s+,", ",", regex=True)
        .str.replace(r",\s+,", ",", regex=True)
        .str.replace(r"\(\s+(\d+)", r"(\1", regex=True)
        .str.replace(r"(\d+)\s+\)", r"\1)", regex=True)
    )

In [22]:
winners = winners.apply(lambda col: col.str.upper() if col.dtype == "object" else col)

In [23]:
names = sorted(winners.Name.dropna().unique())

with open("data/yagp_names.txt", "w") as file:
    file.writelines(
        name + "\n" for name in names
    )

- Misspellings/errors:
    - ALANAGRIFFITH = ALANA GRIFFITH
    - ALTHEA JOHNSON - STAUB
    - ANDREAJONUSAS = ANDREA JONUSAS
    - ELISA D[CARPIO = ELISA D'CARPIO
    - GABRIELLEGIRARD = GABRIELLE GIRARD
    - LOGANHILLMAN = LOGAN HILLMAN
    - MAKAI LEWIS - REES
    - MARIARODRIGUEZ = MARIA RODRIGUEZ
    - PHILIP MARTIN‐NIELSON
    - SHERY MORAY = SHERRY MORAY
    - SHI HANY HUANG = SHI HANG HUANG
    - VICTORIAHASK = VICTORIA HASK
    - WING YAN [IBBY] CHOW
- Names containing commas that need to be fixed:
    - 'CAROLIE, LAUVETZ'
    - 'ALESSANDRO FROLA, 12, MARTINA MANTOVANI, 13'
    - 'VALENTINA LEALI, MASSIMO SONZOGNI'
    - 'NORA CLEMENTE, 16, BRYCE LEE, 16'
    - 'WATMORA CASEY, TATYANA MAZUR'
    - 'JESSICA ODASZ, ANDREA ASTUTO'
    - 'KATIA GARZA, TODD ERIC ALLEN'
    - 'NADIA, TENCER'
- Different Names for the same person:
    - CHEN LI-EN, LIESL = LI-EN, LIESL CHEN ; LIESL CHEN
    - GOH JIA YI, ANU = GOH JIA YI
    - KENNETH SHELBY, JR = KENNETH DUANE SHELBY, JR ; KENNETH DUANE SHELBY JR
    - NADIA VESELOVA TENCER = NADIA VESELOVA-TENCER = NADIA, TENCER ; NADIA VESELOVA-TENCER
    - PHYLICIA, ZI YING CHEW = ZI YING CHEW
    - SOFIA, ZI XUAN LEE = ZI XUAN LEE

In [24]:
winners.loc[
    winners.Name.str.contains("ABIGAIL, BOIVIN", na=False),
    "Name"
] = "ABIGAIL BOIVIN"

winners.loc[
    winners.Name.str.contains("ALANAGRIFFITH", na=False),
    "Name"
] = "ALANA GRIFFITH"

winners.loc[
    winners.Name.str.contains("ANDREAJONUSAS", na=False),
    "Name"
] = "ANDREA JONUSAS"

winners.loc[
    winners.Name.str.contains("BRITTANY, GEORGHEGAN", na=False),
    "Name"
] = "BRITTANY GEORGHEGAN"

winners.loc[
    winners.Name.str.contains("CAROLIE, LAUVETZ", na=False),
    "Name"
] = "CAROLIE LAUVETZ"

winners.loc[
    winners.Name.str.contains("ELISA D[CARPIO", regex=False, na=False),
    "Name"
] = "ELISA D'CARPIO"

winners.loc[
    winners.Name.str.contains("GABRIELLEGIRARD", na=False),
    "Name"
] = "GABRIELLE GIRARD"

winners.loc[
    winners.Name.str.contains("GOH JIA YI, ANU", na=False),
    "Name"
] = "GOH JIA YI"

winners.loc[
    (winners.Name.str.contains("KENNETH SHELBY, JR", na=False)) |
    (winners.Name.str.contains("KENNETH DUANE SHELBY, JR", na=False)),
    "Name",
] = "KENNETH DUANE SHELBY JR"

winners.loc[
    (winners.Name.str.contains("CHEN LI-EN, LIESL", na=False)) |
    (winners.Name.str.contains("LI-EN, LIESL CHEN", na=False)),
    "Name",
] = "LIESL CHEN"

winners.loc[
    winners.Name.str.contains("LOGANHILLMAN", na=False),
    "Name"
] = "LOGAN HILLMAN"

winners.loc[
    winners.Name.str.contains("MARIARODRIGUEZ", na=False),
    "Name"
] = "MARIA RODRIGUEZ"

winners.loc[
    (winners.Name.str.contains("NADIA VESELOVA TENCER", na=False)) |
    (winners.Name.str.contains("NADIA VESELOVA-TENCER", na=False)) |
    (winners.Name.str.contains("NADIA, TENCER", na=False)),
    "Name",
] = "NADIA VESELOVA-TENCER"

winners.loc[
    winners.Name.str.contains("TAYLOR, HOGAN", na=False),
    "Name"
] = "TAYLOR HOGAN"

winners.loc[
    winners.Name.str.contains("TORI, JENNINGS", na=False),
    "Name"
] = "TORI JENNINGS"

winners.loc[
    winners.Name.str.contains("VICTORIAHASK", na=False),
    "Name"
] = "VICTORIA HASK"

winners.loc[
    winners.Name.str.contains("SOFIA, ZI XUAN LEE", na=False),
    "Name"
] = "ZI XUAN LEE"

winners.loc[
    winners.Name.str.contains("PHYLICIA, ZI YING CHEW", na=False),
    "Name"
] = "ZI YING CHEW"

winners.loc[
    winners.Name.str.contains("SHERY MORAY", na=False),
    "Name"
] = "SHERRY MORAY"

winners.loc[
    winners.Name.str.contains("SHI HANY HUANG", na=False),
    "Name"
] = "SHI HANG HUANG"

# winners.loc[
#     (winners.Name.str.contains("ABIGAIL BOIVIN", na=False)) |
#     (winners.Name.str.contains("ALANA GRIFFITH", na=False)) |
#     (winners.Name.str.contains("ALTHEA JOHNSON - STAUB", na=False)) |
#     (winners.Name.str.contains("ANDREA JONUSAS", na=False)) |
#     (winners.Name.str.contains("BRITTANY GEORGHEGAN", na=False)) |
#     (winners.Name.str.contains("ELISA D'CARPIO", na=False)) |
#     (winners.Name.str.contains("GABRIELLE GIRARD", na=False)) |
#     (winners.Name.str.contains("GOH JIA YI", na=False)) |
#     (winners.Name.str.contains("KENNETH DUANE SHELBY JR", na=False)) |
#     (winners.Name.str.contains("LIESL CHEN", na=False)) |
#     (winners.Name.str.contains("LOGAN HILLMAN", na=False)) |
#     (winners.Name.str.contains("MARIA RODRIGUEZ", na=False)) |
#     (winners.Name.str.contains("MAKAI LEWIS - REES", na=False)) |
#     (winners.Name.str.contains("PHILIP MARTIN‐NIELSON", na=False)) |
#     (winners.Name.str.contains("TAYLOR HOGAN", na=False)) |
#     (winners.Name.str.contains("TORI JENNINGS", na=False)) |
#     (winners.Name.str.contains("VICTORIA HASK", na=False)) |
#     (winners.Name.str.contains("ZI XUAN LEE", na=False)) |
#     (winners.Name.str.contains("ZI YING CHEW", na=False)) |
#     (winners.Name.str.contains("WING YAN [IBBY] CHOW", regex=False, na=False)),
#     "is_name"
# ] = "person"

In [25]:
winners[winners.Name.str.contains("ALEKSEY", na=False)]

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
3333,ALEKSEY BABAYEV,ACADEMY OF INTERNATIONAL BALLET AND PERFORMING...,2006,"GREENVILLE, SC",TOP 12,PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,NaN,NaN
18314,ALEKSEY AND INESSA PLEKHANOV,NaN,2016,"PHILADELPHIA, PA",OUTSTANDING TEACHER AWARD,NaN,NaN,NaN,NaN,SPECIAL AWARDS

- Inconsistent patterns for recording names:
    - First Name Last Name(s)
    - Last Name, First Name
    - First Name Last Name, [US state]
    - First Name Middle Name(s) and Last Name(s)
    - [1st person] & [2nd person]
    - [1st person], [2nd person]
    - [1st person] (age), [2nd person] (age)
    - (age)
    - [1st person] age, [2nd person] age (where age isn't in parentheses)
    - First Name Last Name (age), (dance that the person/people performed)
    - dance that the person/people performed, ([1st person], [2nd person])

In [26]:
# winners[winners.Name.str.contains("&", na=False)]

In [27]:
# winners[winners.Name.str.contains("& &", na=False)]

In [28]:
# winners[winners.Name.str.contains(r"\bAND\b", na=False)]

- & and "AND" separates names, but some rows have one too many & with whitespace in the middle (& &) 
    - some dances have "AND" in them too :(
        - So replace "&", "& &", and " AND" with a comma (space between name/dance to deal with whitespace)
        - Don't .str.split() on commas just yet, since dances also have commas (need to distinguish what has dancer names and what are names of dances)
- Removing ages and other dances in parentheses, but there's sometimes a hanging comma (ends in comma)

In [29]:
def split_names(string):
    if pd.isna(string):
        return string  # keep NaN
    
    if isinstance(string, str):
        return [s.strip() for s in string.split("&")]
    
    return string

winners.Name = winners.Name.str.replace(r"& &", "&")
winners.Name = winners.Name.apply(split_names)
winners = winners.explode("Name", ignore_index=True)

In [30]:
winners["Names_resolved"] = winners.Name.str.replace(r" \bAND\b", ",").str.strip()
winners["Names_resolved"] = winners.Names_resolved.str.replace(r"\(.*\)", "", regex=True).str.strip()
winners["Names_resolved"] = winners.Names_resolved.str.replace(r",$", "", regex=True).str.strip()

In [31]:
winners["Names_resolved"] = winners["Names_resolved"].str.split(",")

winners[~winners.Names_resolved.isna()]

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category,Names_resolved
2,8+3,INWOOD DANCE COMPANY,2000,"WASHINGTON, DC",3RD PLACE (TIE),NaN,ENSEMBLES,NaN,NaN,NaN,[8+3]
3,CABARET,"DANCE CONSERVATORY, DE",2000,"WASHINGTON, DC",3RD PLACE (TIE),NaN,ENSEMBLES,NaN,NaN,NaN,[CABARET]
4,MAKE THEM HEAR YOU,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",2ND PLACE,NaN,ENSEMBLES,NaN,NaN,NaN,[MAKE THEM HEAR YOU]
5,CAPRICE,"DANCE CONSERVATORY, DE",2000,"WASHINGTON, DC",1ST PLACE,NaN,ENSEMBLES,NaN,NaN,NaN,[CAPRICE]
6,"KORY GLATMAN, NJ",NaN,2000,"WASHINGTON, DC",3RD PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,"[KORY GLATMAN, NJ]"
...,...,...,...,...,...,...,...,...,...,...,...
43515,GERDA'S RIVER JOURNEY,"BAYER BALLET ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"BAYER BALLET ACADEMY, CA",LARGE ENSEMBLES,NaN,[GERDA'S RIVER JOURNEY]
43516,DANCE FOR SIX,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",LARGE ENSEMBLES,NaN,[DANCE FOR SIX]
43517,COPPELIA FRIENDS DANCE,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",LARGE ENSEMBLES,NaN,[COPPELIA FRIENDS DANCE]
43518,KIRA FARGAS,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,[KIRA FARGAS]
43519,HADASSAH PERRY,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,[HADASSAH PERRY]

In [32]:
names = winners[winners.Name.str.contains(",", na=False) == False].Name.unique()

winners.loc[
    ((winners.Names_resolved.str[1].str.strip() + " " + winners.Names_resolved.str[0].str.strip()).isin(names)), 
    ["Names_resolved"]
] = winners.Names_resolved.str[1].str.strip() + " " + winners.Names_resolved.str[0].str.strip()

winners.loc[
    ((winners.Names_resolved.str[0].str.strip() + " " + winners.Names_resolved.str[1].str.strip()).isin(names)), 
    ["Names_resolved"]
] = winners.Names_resolved.str[0].str.strip() + " " + winners.Names_resolved.str[1].str.strip()

In [33]:
yt = winners.Names_resolved.explode()
yt[~yt.isna()]

6                 KORY GLATMAN
6                           NJ
87               MELISSA LORRY
87                          MA
124      ARIZONA BALLET SCHOOL
                 ...
43229                  MEASURE
43229                      CUT
43244                     SPIN
43244                  MEASURE
43244                      CUT
Name: Names_resolved, Length: 553, dtype: object

- US state abbreviations followed after names need to be removed
- ages not in parentheses need to be removed

In [34]:
patterns = re.compile(
    r"^(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC|\d{1,2})$"
)

# def remove_state_age(x):
#     if isinstance(x, list) and len(x) == 2:
#         first, second = x
#         if isinstance(second, str) and patterns.fullmatch(second.strip()):
#             return first.strip()
        
#     if isinstance(x, list) and len(x) == 4:
#         first, second, third, fourth = x
#         if second.strip().isdigit() & fourth.strip().isdigit():
#             return [first.strip(), third.strip()]
#     return x

def remove_state_age(x):
    if not isinstance(x, list):
        return x
    
    cleaned = []
    for i in x:
        i = i.strip()
        if patterns.fullmatch(i):
            continue
        cleaned.append(i)

    return cleaned

winners["Names_resolved"] = winners["Names_resolved"].apply(remove_state_age)

In [35]:
for i in winners.Names_resolved[~winners.Names_resolved.isna()].value_counts().index:
    if not isinstance(i, list):
        print(i)

COPPELIA PAS DE DEUX
DON QUIXOTE PAS DE DEUX
ALEXANDRIA MARX
HARLEQUINADE PAS DE DEUX
RACHEL ROHRICH
MASUMI YOSHIMOTO
PAS DE DEUX GRAND PAS CLASSIQUE
SWAN LAKE PAS DE TROIS
ODALISQUES LE CORSAIRE
RYLAND ACREE III
LAUREN LEB
JASMINE JIMISON
SILVI LYBBERT
ORLANDO BALLET SCHOOL FL
JESLYN CHEN
GENEVIEVE COOVREY
ALL AMERICAN CLASSICAL BALLET SCHOOL FL

- Classifying what entries have people's names:

In [36]:
dances_and_schools = list(winners.School.dropna().unique())
print("GINGER SMITH" in dances_and_schools)

True

In [37]:
# winners[winners.Name.str.contains(",", na=False)].Name.unique()

In [38]:
name_dances_and_schools = [
'ARIZONA BALLET SCHOOL, AZ',
'BILLS, BILLS, BILLS',
'BROTHER, CAN YOU SPARE A DIME',
'ADAMS SCHOOL OF DANCE, VT',
'PAS DE DEUX, "GISELLE", ACT III',
'ODALISQUES, LE CORSAIRE',
'GRANDE PAS DE DEUX, LE CORSAIRE',
'ENGLISH STRING SUITE, 4TH',
'ODALISQUE, LE CORSAIRE',
'CONCERTO GROSSO, 4TH MOVEMENT',
'SWAN LAKE, PAS DE TROIS',
'LA FILLE MAL GARDEE, THE CLOGS DANCE',
'MIRTH, FIRST MOVEMENT',
'WHEAT PAS DE DEUX, COPPELIA',
'SODA BALLET ACADEMY, JAPAN',
'GRAND PAS CLASSIQUE, PAS DE DEUX',
'PERHAPS, PERHAPS, PERHAPS',
'COPPELIA, THE DOLL',
'IMPACT DANCE OF ATLANTA, GA',
'MORNING STAR DANCE ACADEMY OF ATLANTA, GA',
'INTERNATIONAL BALLET ACADEMY, NC',
'AKHMEDOVA BALLET ACADEMY, MD',
'INTERNATIONAL CITY SCHOOL OF BALLET, GA',
'ORLANDO BALLET SCHOOL, FL',
'JESU, JOY!',
'PAS DE DEUX FROM FLOWER FESTIVAL AT GENZANO, CA',
"BOYS' DANCE FROM THE LIFE OF KING ARTHUR, A MEDEIVAL FANTAISIE",
'FLAMES OF PARIS, BASQUES DANCE',
'YES, JESUS LOVES EVEN ME!',
'WE, ALWAYS WE',
'GENTLY FALLING, FLOATING DOWN',
'DON QUIXOTE, PAS DE DEUX',
'COPPELIA, PAS DE DEUX',
'LE CORSAIRE, ACT III PAS DE DEUX',
'GISELLE, PEASANT PAS DE DEUX ACT I',
'ACTEON, PAS DE DEUX',
'DANCE WITH SWORDS, FROM GAYANEE',
'CUBA LINDA, CUBA HERMOSA...',
'HARLEQUINADE, PAS DE DEUX',
'FLOWER FESTIVAL IN GENZANO, PAS DE DEUX',
'POUR TOI, MARCEAU',
'SOMETHING, ANYTHING, NOTHING',
'LE CORSAIRE, ACT III',
"K-BALLET ART, LADANSE BALLET, BLUET BALLET ACADEMY, EWHA BALLET ETOILE, YONGTONG E-WHA BALLET ACADEMY, KIM HYE YOUNG BALLET ACADEMY, LEE WONJU BALLET ACADEMY, JS BALLET, POSE BALLET ACADEMY, S.M. BALLET",
"ACADEMY OF INT'L BALLET, PA",
'INTERNATIONAL BALLET THEATER ACADEMY, PA',
'TATIANA AKINFIEVA DANCE ACADEMY, DE',
'SHOKO KITAGUCHI BALLET STUDIO, JAPAN',
'LE CORSAIRE, ACT III PDD',
'SLAVE, LE CORSAIRE',
'THE DALLAS CONSERVATORY, TX',
'DANCE INSTITUTE, TX',
'ELITE CLASSICAL COACHING, TX',
'BALLET CONSERVATORY, TX',
'ALLEGRO WEST ACADEMY OF DANCE, TX',
'ART BALLET ACADEMY, TX',
'BALLET ACADEMY OF TEXAS, TX',
'BALLET CENTER OF FORT WORTH, TX',
'DALLAS BALLET CENTER, TX',
'DANCE INDUSTRY PERFORMING ARTS CENTER, TX',
'MARINA ALMAYEVA SCHOOL OF CLASSICAL BALLET, TX',
'PREMIERE BALLET ACADEMY, TX',
'KOLTUN BALLET BOSTON, MA',
'ROCKWELL DANCE CENTER, CT',
'CHANGING NOTHING, NOTHING CHANGES',
'LOOKING BACK, GOING FORWARDS',
'SUMMIT DANCE SHOPPE, MN',
'CHRISTINE RICH STUDIO DANCE ACADEMY, IL',
'ILLINOIS DANCE CONSERVATORY, IL',
'CHICAGO BALLET CONSERVATORY, IL',
'INDIANA BALLET CONSERVATORY, IL',
'NORTHPOINTE DANCE ACADEMY, OH',
'CORNELIUS, THE SELLER OF BALLOONS',
'A STORM INSIDE US, SILENCE OUTSIDE',
'CLASSICAL BALLET ACADEMY, OR',
'CLASSICAL DANCE ACADEMY, CA',
'SIMPLY BALLET, CANADA',
'EMERALD BALLET ACADEMY, WA',
'INSPIRE DANCE CENTRE, OR',
'THE DANCE CONSERVATORY WEST VANCOUVER, CANADA',
'SULTANOV RUSSIAN BALLET ACADEMY, OR',
'HOWARD W. BLAKE HIGH SCHOOL, FL',
'ALL AMERICAN CLASSICAL BALLET SCHOOL, FL',
'RENNER BALLET ACADEMY, NC',
'THE THINNING, THE LIGHT THAT BINDS US, TREMORS',
'MIRROR, MIRROR',
'CLASSICAL BALLET CENTRE, SC',
'CARY BALLET CONSERVATORY, NC',
'ACADEMY OF RUSSIAN BALLET, VA',
'UNCSA PREPARATORY DANCE PROGRAM, NC',
'METROPOLITAN SCHOOL OF THE ARTS ACADEMY, VA',
'BALLET INSTITUTE OF ATLANTA, GA',
'SWIM,SWAM,SWUM',
'DEGAS DANCE STUDIO, CA',
"BOBBIE'S SCHOOL OF PERFORMING ARTS, CA",
'NORTH COUNTY ACADEMY OF DANCE, CA',
'SOUTH COAST CONSERVATORY, CA',
'CALIFORNIA DANCE ACADEMY, CA',
'TUSTIN DANCE CENTER, CA',
'THE PREMIER BALLET SCHOOL OF ORANGE COUNTY, CA',
'SHIRLEY WINTERS BALLET, CA',
'INLAND PACIFIC BALLET ACADEMY, CA',
'THE SARASOTA CUBAN BALLET SCHOOL, FL',
"JACQUELINE'S SCHOOL OF BALLET, UT",
'BALLET WEST ACADEMY, UT',
'LOS ANGELES BALLET ACADEMY, CA',
'MOGA CONSERVATORY OF DANCE, UT',
'ROCKY MOUNTAIN BALLET ACADEMY, CO',
'LITTLETON BALLET ACADEMY, CO',
'STUDIO R BALLET, AZ',
'COLORADO BALLET ACADEMY, CO',
'CLASSICAL BALLET ACADEMY, CO',
'INDIANA BALLET CONSERVATORY, IN',
'MAIN STREET BALLET COMPANY, IL',
'DAVID MATTHEW STUDIOS, MI',
'DIANA EVANS SCHOOL OF DANCE, KY',
"VALENTINA'S SCHOOL OF BALLET, MI",
'DANCE ACADEMY OF LIBERTYVILLE, IL',
'SOUTHOLD DANCE THEATER, IN',
'TURNING POINTE DANCE STUDIO, MA',
'GREENWICH BALLET ACADEMY, CT',
'DANCING ARTS CENTER, MA',
'THE HARTT SCHOOL, CT',
'SKYRA STUDIOS, FL',
'CLASSICAL BALLET OF WNY, NY',
'VOILÀ, NOUS VOICI!',
'WITH YOU, ALWAYS',
'THE CHERRY COUNTESS, CIPOLINO',
'PAST, PRESENT AND FUTURE',
'NON, RIEN DE RIEN',
'STILL, WE FALL',
'SAME BEAT, TWICE',
'STRONG, CALM, SLOW',
'SPIN, MEASURE, CUT',

# extracted dances from mixed entries
'THE SLEEPING BEAUTY GRAND PAS ACT III',
'LA BAYADERE',
'SATANELLA',
'LA FILLE MAL GARDEE',
'HARLEQUINADE',
'COPPELIA',
'MOSZKOVSKY WALTZ',
'THE CAVALRY HALT',
'FLAMES OF PARIS',
"LE CORSAIRE, PAS D'ESCLAVE"
]


entry = name_dances_and_schools[43]
del name_dances_and_schools[43]
split_schools = [x.strip() for x in entry.split(",")]

dances_and_schools = np.unique(dances_and_schools + name_dances_and_schools + split_schools)
dances_and_schools

array(['1 DANCE ACADEMY', '1-2-3-4', '8 COUNT DANCE, OH', ...,
       '\xa0ART OF TECHNIQUE, VA', 'ÉCOLE SUPÉRIEURE DE BALLET DU QUÉBEC',
       'ÉCOLE SUPÉRIEURE DE BALLET DU QUÉBEC, CANADA'], dtype='<U170')

- Cleaning up the names column to just get people's names:

In [39]:
# winners = winners.explode("Names_resolved")

In [40]:
# winners

In [41]:
# for name in sorted(winners.Name.dropna().unique()):
#     print(name)

In [42]:
# for name in winners.Name.dropna().unique():
#     print(name)

In [43]:
# for name in sorted(
#     winners[
#         (winners.Name.str.contains(",", na=False)) & 
#         (winners.is_name == "person") 
#     ]["Name"].unique()
# ):
#     print(name)

In [44]:
# for name in sorted(winners[
#     (winners.is_name == "person") |
#     (winners.is_name == "people")
# ]["Name"].unique()):
#     print(name)

# Dancers:
- classifications: person, people

In [45]:
dancers = winners.dropna(subset="Name")
dancers.shape

(42966, 11)

## Finding a column to filter people/person from:

- Category:
    - ENSEMBLES ; DANCES
    - LARGE ENSEMBLES ; DANCES
    - PAS DE DEUX ; DANCES AND NAMES
    - SMALL ENSEMBLES ; DANCES
    - DUETS & TRIOS ; DANCES

In [46]:
sorted(dancers[dancers["Category"].str.contains(r"PAS DE DEUX", na=False)].Name.unique())

['A LITTLE LIFE',
 'ANDANTE',
 'APPASSIONATA',
 'ARABIAN PAS DE DEUX FROM THE NUTCRACKER',
 'ASHLEY LARACEY',
 'BENJAMIN HARBOR',
 'BLACK SWAN PAS DE DEUX FROM SWAN LAKE',
 'BO BUSBY',
 'CINDERELLA',
 'CLAIRE DE LUNE',
 'CONVERSATIONS WITH MYSELF',
 'DOLLS VAR. FROM "THE NUTCRACKER"',
 'DON QUIXOTE',
 'END OF MAY',
 "IT'S A GOOD DAY",
 'KYRA HOMERES',
 'LA BAYADERE',
 'LA FILLE MAL GARDEE',
 'LA FILLE MAL GARDEE PAS DE DEUX',
 'LES SYLPHIDES',
 'LIBERTANGO',
 'OFF',
 'PAS DE DEUX FROM "PAQUITA"',
 'PAS DE DEUX FROM COPPELIA',
 'PAS DE DEUX FROM DON QUIXOTE',
 'PAS DE DEUX FROM FLAMES OF PARIS',
 'PAS DE DEUX FROM FLOWER FESTIVAL AT GENZANO',
 'PAS DE DEUX FROM GISELLE',
 'PAS DE DEUX FROM GRANDUATION BALL',
 'PAS DE DEUX FROM HARLEQUINADE',
 'PAS DE DEUX FROM HARLIQUENADE',
 'PAS DE DEUX FROM LA FILLE MAL GARDEE',
 'PAS DE DEUX FROM LE CORSAIRE',
 'PAS DE DEUX FROM NUTCRACKER',
 'PAS DE DEUX FROM PAQUITA',
 'PAS DE DEUX FROM SATANELLA',
 'PAS DE DEUX FROM TALISMAN',
 'PAS DE DEUX FROM THE NUTCRACKER',
 'PAS DE DEUX, "GISELLE", ACT III',
 'PIANO SONATA #14',
 'PLAYFUL MEMORY',
 'PLENTITUDO',
 'RED RIDING HOOD AND THE WOLF',
 'REQUIEM',
 'ROBERT DUNBAR',
 'SATANELLA',
 'SHELBY RATCHFORD LA BAYADERE',
 'SPLIT',
 'SPRING WATERS',
 'SYMBION',
 'THE MAN I LOVE',
 'THE MUSIC OF THE NIGHT',
 'UN RESPIRO',
 'VARIATION FROM "COPPELIA"',
 'VARIATION FROM LA ESMERELDA',
 'WENDY']

In [47]:
dances = list(dancers[dancers["Category"].str.contains(r"ENSEMBLES|LARGE ENSEMBLES|SMALL ENSEMBLES|DUETS & TRIOS", na=False)].Name)

- Division / Position:
    - LARGE ENSEMBLES ; DANCES
    - SMALL ENSEMBLES ; DANCES AND NAMES
    - PAS DE DEUX ; DANCES AND NAMES
    - ENSEMBLES ; DANCES AND NAMES
    - DUET/TRIO ; DANCES

In [48]:
sorted(dancers[dancers["Division / Position"].str.contains(r"PAS DE DEUX", na=False)].Name.unique())

['ACE ACKET',
 'ADRIANA MARQUIQGUI CASADO',
 'AIDAN FUNG',
 'AINARA REINA PIQUERAS',
 'ALEJANDRO TIRADO ARADILLA',
 'ALESSANDRO MARINI',
 'ALEX GLADKOWSKI',
 'ALEX RODES TORA',
 'ALEXANDER VENS',
 'ALIANA NASSOS',
 'ALIANNA NASSOS',
 'ALICE LI',
 'AMARIS PONDER',
 'AMELIA WU',
 'ANATOLI BODROV',
 'ANDREW HALVERSON',
 'ANIYAH GUERRERO',
 'ANNA SURAPANENI',
 'ANTONELLA VILLA',
 'AQUA MARINE',
 'AURORA',
 'AVA KLOPPE',
 'AVA WHITEHURST',
 'BEN BIGELOW',
 'BEN HOLTON',
 'BEN MEYER',
 'BLAKELY BURNS',
 'BLUE BIRD SLEEPING BEAUTY',
 'BRAELYN SMITH',
 'BRAHMS VIOLIN CONCERTO',
 'BROOKLYN WHITLEY',
 'BRUNO COKELISS',
 'BRYCE YOUNG',
 'BRYNN TRAMLEY',
 'CAITLYN DIONEDA',
 'CAMILA ORTIZ MACIAS',
 'CANDICE YEO ZHI JING',
 'CAROLINE MCGOWAN',
 'CASIMIR FIRLIT',
 'CAYLON HULL',
 'CHAE YEON KIM',
 'CHARLEY TOSCANO',
 'CHARLOTTE BLAKE',
 'CHASING THE SAME MOMENT',
 "CHIARA D'ALO",
 'CHLOE FAN',
 'CLARA CRANE',
 'CLAUDIA TINARI',
 'CLAY KINLER',
 'CONSTANCE CABANES',
 'CONSTANCE MEEK',
 'DANIEL BERBERIAN',
 'DANIEL MILOSSERDOV',
 'DANNY PORTILLO',
 'DELANEY KNIPS',
 'DIYA SAGAR',
 'DON QUIXOTE, PAS DE DEUX',
 'DOROTEJA JURKUTE',
 'DULCIANNA JONAK',
 'EAST',
 'EASY JOY',
 'EDUARDO RAMOS MACHADO',
 'ELISA FILIPETTA',
 'EMMA BOGGS',
 'EMMA ESTREMADOYRO',
 'EMMA HAMBURGER',
 'EMMA LI',
 'ENARA ARTOLA REBOLLO',
 'ENZO MORENO DELFINO',
 'FONDU',
 'FOR ALL PAS DE DUEX',
 'FRAMED',
 'GEORGIA REED',
 'GIBSON BAGGETT',
 'GIGI NATHO',
 'GINEVRA LIU',
 'GIOELE SALMI',
 'GISELE ELISE WILSON',
 'GISELLE MINER',
 'GLASS HALF FULL',
 'GRACE WAN',
 'HARLEQUINADE',
 'HERKUS ZATAVECKAS',
 'HINANO YOSHITAKE',
 'HO YEON NAM',
 'HUGO GARCIA RODRIGO',
 'IAN PEREZ',
 'IAN TURNER',
 'IN A SPIRAL',
 'ISAAC PLASENCIA',
 'ISABELLA KLEMOWITS',
 'IVANA DEDOVICH',
 'IVY NAKAUYE',
 'JADE CRANE',
 'JAMARI CUNNINGHAM',
 'JAMES AUGUSTUS LEINAUER',
 'JAYDEN VAN',
 'JEAN MARCO SANZ MARTINEZ',
 'JERRY LAVIGNE',
 'JOHNSTON KRAFT',
 'JONATHAN FLEISHMAN',
 'JONES HARTLEY',
 'JORDAN LAVIGNE',
 'JOSE ALEJANDRO CINCIRIPINI',
 'JOSEPH WALLEN',
 'JULIANA PETRIE',
 'JURGI ERRANDONEA OREJA',
 'JUSTIN EGAN',
 'KAI HANSER',
 'KAI VITOLO',
 'KAMILLA LATIFI',
 'KARA CRUEY',
 'KARIN TSUKAMOTO',
 'KARSON STUBBS',
 'KATSIARYNA LIPKO',
 'KIRILL KOPAIEV',
 'KIRILL LAPTSIONAK',
 'KYLER LAMAN',
 'LA FILLE FRIENDS',
 'LANE WHITEHURST',
 'LAURA ALFONSINO',
 'LE CORSAIRE',
 'LE CORSAIRE ODALISQUES PAS DE TROIS',
 'LEONOR NEVES',
 'LIAM BOOBAR',
 'LIAM WALTERS',
 'LIESL KRAFT',
 'LIZZIE MATTHES',
 'LUANA AZEVEDO',
 "LUCA D'ANGELO",
 'LUNA ALVAREZ BALLESTEROS',
 'LYDIA WOODWARD',
 'LÉON GARNIER',
 'MADELEINE SIMMONS',
 'MADELINE CHANG',
 'MADELYN MURPHY',
 'MAEVE CALLAHAN',
 'MANUEL ESPINOSA CARRASCO',
 'MARCO RODELLA',
 'MARGARIDA RODRIGUES',
 'MARIO ALCALÁ',
 'MASK',
 'MATTHEW CONWAY',
 'MAXWELL WINN',
 'MCKINZIE NAMAULEG',
 'MEGAN JARVIS',
 'MEGAN SAVAGE',
 'MELYNA AUDEGOND',
 'MERCE MEYNARDIE',
 'MILANIA LEONE',
 'MINJIN KIM',
 'MORGAN WEAVER',
 'NAOMI GASSER',
 'NATALIE FRY',
 'NIA NICOZISIS',
 'NIKOLAS PARPERIDES',
 'NOAH',
 'NOAH NAZARIAN',
 'NOFAR AHARONI',
 'OAKLEY DUNCAN',
 'OLIVER TEO',
 'OLIVIA KEY',
 'OWEN SIMMONS',
 'PAS DE TROIS FROM PAQUITA',
 'PETER AZEVEDO',
 'PRESTON PERRY',
 'PULSAR',
 'QIANG DI LIU YANG',
 'RAELYN VINCENT',
 'REIRI SHIBAYAMA',
 'ROMULO SOARES',
 'RYOMA ASADA',
 'SACHI OZA',
 'SARAH MAIONE',
 'SCARLETT PAULETTO',
 'SEONGMO KOO',
 'SHAI-LEE GLUCK',
 'SHANE WEXELMAN',
 'SHANNON LANIER',
 'SHAPELESS CLASH',
 'SILVIA LOARCE DIES',
 'SILVIA RIVES RIVES',
 'SOFIA BERNARDI',
 'SOFIA PEREIRA AZEVEDO',
 'SOPHIE SEGUIN',
 'SOSUKE NOJIRI',
 'SPENCER COLLINS',
 'STEPAN MAKHRAYEV',
 'STEPHEN KESSLER',
 'TAKE IT ALL',
 'TATIANA CHEN',
 'TEO MUNOZ FONTEDEGLORIA',
 'THOMAS WILCUTTS',
 'TOBIAS WEBER',
 'TRUST',
 'TYLOR XU',
 'VALENTINA MASCINI LESCARY',
 'VALENTINA MASCINI LESCAY',
 'VALERIE GRIVALSKY',
 'WHO AM I',
 'WILLIAM BESSLER',
 'WILLIAM JALKUT',
 'WITH YOU, ALWAYS',
 'WONDER',
 'WYATT TESSANDORE',
 'YON SILVER',
 'YUSEI YOSHITAKE',
 'ZEPH BRINTON',
 'ZOE CENTELLES SÁNCHEZ',
 'ZOE KOLLINIATIS']

In [49]:
dances += list(dancers[dancers["Division / Position"].str.contains(r"LARGE ENSEMBLES|DUET/TRIO", na=False)].Name)

- Dance Category:
    - ENSEMBLES ; MOSTLY DANCES AND NAMES
    - PAS DE DEUX ; DANCES AND NAMES
    - LARGE ENSEMBLES ; DANCES
    - SMALL ENSEMBLES ; DANCES
    - ENSEMBLES & PAS DE DEUX ; MOSTLY NAMES (KOREAN DANCERS) AND SOME DANCES
    - DUETS & PAS DE DEUX ; DANCES
    - DUET/TRIO ; DANCES

In [50]:
sorted(dancers[dancers["Dance Category"].str.contains("ENSEMBLES", na=False)].Name.unique())

['1LEDGE',
 '3 SISTERS',
 '3RD MOVEMENT FROM "PLAZA DEL FEUGO"',
 'A BOY IN LOVE',
 'A CELLO SONG DANCE',
 'A CHOPIN WALTZ',
 'A DANCE',
 'A DIFFERENT ANGLE',
 'A DIGA DOO',
 'A GLACIER',
 'A HUG TO CALL HOME',
 "A L'AREE DE KIRUNA",
 'A LIGHT IN THE DARKNESS',
 'A LITTLE CHOPIN MAZURKA',
 "A MIDSUMMER NIGHT'S DREAM - FAIRIES",
 "A QUEEN'S REIGN",
 'A SHORE NEVER REACHED',
 'A SONG FOR YOU',
 'A STORM INSIDE US, SILENCE OUTSIDE',
 'A STRANGE BEAUTY',
 'A STREAM WITHIN',
 'A STRONG FORCE',
 'A VAGUE SENSE OF PERSISTENCE',
 'A-FLAT',
 'ABSOLUTION',
 'ABSTRACT #17',
 'ACADEMY OF BALLET ARTS FL',
 "ACADEMY OF INT'L BALLET, PA",
 'ACADEMY OF RUSSIAN BALLET, VA',
 'ACT II PAS DE DEUX FROM GISELLE??',
 'ACTEON, PAS DE DEUX',
 'ADAGIO',
 'ADIR ADIRIM',
 'ADORATION',
 'ADRIFT',
 'AERIAL PORTRAIT',
 'AETHER',
 'AFRIKA',
 'AFTER THE FALL',
 'AFTER THE SHOCK',
 'AFTER THOUGHT',
 'AFTERNOON INTERLUDE',
 'AGGRANDIZMENT',
 'AIRBORNE',
 'AKHMEDOVA BALLET ACADEMY, MD',
 'AL SUON DI TARANTELLA',
 'ALEGRIA',
 'ALEGRO',
 'ALL',
 'ALL AMERICAN CLASSICAL BALLET SCHOOL FL',
 'ALL AMERICAN CLASSICAL BALLET SCHOOL, FL',
 'ALL ENSEMBLES',
 'ALL FOR ONE',
 'ALL OF THEIR PIECES',
 'ALL OF THEIR WORK',
 'ALL PIECES',
 'ALL THEIR PIECES',
 'ALLEGRETTO',
 'ALLEGRO',
 'ALLEGRO DANGEROSO',
 'ALLEGRO DINAMICO',
 'ALLEGRO WEST ACADEMY OF DANCE, TX',
 'ALLIANCE',
 'ALMENO UN MILIONE DI SCALE',
 'ALOFT',
 'AMANHECER',
 'AMAZON',
 'AMELIE',
 'AMERICANO',
 'AMERICANO 2',
 'AMICA',
 'AMORE ARGENTINE',
 'AN AFFAIR OF THE HEART',
 'AN AFFIAIR OF THE HEART',
 'AND STILL THEY DRIFTED',
 'ANI-MA',
 'ANIMATED FRESCOES',
 'ANIMUS FORM',
 'ANOTHER VISION',
 'ANTICS OF AGNES',
 'APOCALYSIS',
 'APOLOGY NOT ACCEPTED',
 'APRES MOI',
 'AQUA VITE',
 'ARAGAON JOTA',
 'ARAGON JOTA',
 'ARANDA',
 'ARCHITECT OF THE MIND',
 'ARIOSO',
 'ARMENIAN FOLK DANCE',
 'ART BALLET ACADEMY, TX',
 'ART-TIST',
 'AS AMIGAS DE JULIETA',
 'AS THEY SAY',
 'ATLANTA ACADEMY OF BALLET AND DANCE GA',
 'ATTACHMENTS OF AVOIDANCE',
 'AVE MARIA',
 'AWAKE MY SOUL',
 'AWAY',
 'BABAE',
 'BACCHAE',
 'BACH CONCERTO',
 'BACH PRELUDE',
 'BACH STREET PRELUDE',
 'BACH TRIO',
 'BACK TO THE BEGINNING',
 'BAILANDO CON HUEVOS',
 'BAILE DE ESPANA',
 'BALLADA PARA MI MUERTE',
 'BALLANDO CON ROSINA',
 'BALLATA',
 'BALLET ACADEMY OF TEXAS, TX',
 'BALLET BAROQUE',
 'BALLET CENTER OF FORT WORTH, TX',
 'BALLET CONSERVATORY, TX',
 'BALLET EAST FL',
 'BALLET INSTITUTE OF ATLANTA, GA',
 'BALLET WEST ACADEMY, UT',
 'BALLETTO DETTO - PAS DE QUATRE',
 'BANYAN',
 'BARYNIA',
 'BASED ON E. A. POE - "THE RAVEN"',
 'BASED ON E. A. POE - THE RAVEN',
 'BATHTIME IN CLERKENWELL',
 'BATTIBECCHI',
 'BEAUTY MEASURED IN TIME',
 'BEGIN',
 'BELLA DONNA',
 'BELLA TARANTELLA',
 'BELLES AND BUMPERSHOOTS',
 'BELONGING',
 'BENEDICTION',
 "BERNINI'S ANGELS",
 'BETWEEN FOUR',
 'BETWEEN THE TREES',
 'BIRD FLU',
 'BLACK IS THE COLOR',
 'BLACK VEIL',
 'BLAH BLAH BLAH',
 'BLOOMING',
 'BLOOMING JASMINE FLOWERS',
 'BLOSSOM',
 'BLUE',
 'BLUE BIRD PAS DE DEUX FROM SLEEPING BEAUTY',
 'BLUEBIRD PAS DE DEUX FROM SLEEPING BEAUTY',
 'BLUET BALLET ACADEMY',
 'BOADICEA',
 'BOAT TURNS TOWARD THE PORT',
 "BOBBIE'S SCHOOL OF PERFORMING ARTS, CA",
 'BOHEMIAN RAPSODY',
 'BOLERO',
 'BONZAI',
 'BOTH SIDES NOW',
 'BOWSPIRIT',
 'BOYOUNG KIM 김보영',
 "BOYS' DANCE FROM THE LIFE OF KING ARTHUR, A MEDEIVAL FANTAISIE",
 'BRAHMS SUITE # 1',
 'BRAMAN',
 'BREAK AWAY',
 'BREAKING FREE',
 'BREAKING THE FOLD',
 'BRIDGES',
 'BRIO',
 'BROKEN LIMIT',
 'BROKEN SORROW',
 'BROTHERS',
 'BROTSJOR',
 'BROTSTER',
 'BUKOVINIAN LARK',
 'BURBANK SCHOOL OF THE BALLET',
 'BUTTERFLY SERANADE',
 'BY MY SIDE',
 'CALIFORNIA ARTS ACADEMY SEVERANCE CONSERVATORY',
 'CALIFORNIA DANCE ACADEMY, CA',
 'CALIPSO',
 'CANDY CANE VARIATION FROM THE NUTRACKER SUITE',
 'CANDY KISSES',
 'CANON INVERSO',
 'CANONE INVERSO',
 'CANTATA',
 'CANVAS',
 'CAPITA-LIS-MONSTER',
 'CAPULLITO',
 'CARMEN',
 'CARMEN SUITE',
 'CARRY YOU',
 'CARY BALLET CONSERVATORY, NC',
 'CATCH ME IF YOU CAN',
 'CATHEDRALS',
 'CAUCASSIAN DANCE',
 'CAUGHT',
 'CENTURY',
 'CF DANCE ACADEMY',
 'CHAMPAGNE GALOP',
 'CHAMPIONS RISING',
 'CHANGING NOTHING, NOTHING CHANGES',
 'CHANSON DE MATIN',
 'CHASED INTO THE MOMENT',
 'CHASING INK',
 'CHASING SOULS',
 'CHEEK TO CHEEK',
 'CHERRIES',
 'CHIAROSCURO',
 'CHICAGO BALLET CONSERVATORY, IL',
 'CHILDHOOD',
 "CHILDREN'S DANCE FROM LA FILLE MAL GARDEE",
 "CHILDREN'S MAZURAK FROM PAQUITA",
 "CHILDREN'S MAZURKA FROM PAQUITA",
 "CHILDREN'S PAS DE TROIS",
 "CHILDREN'S TRIO FROM VAMPIRE BALL",
 'CHINA BLUE',
 'CHINA DOLLS',
 'CHINESE DANCE',
 'CHINESE DOLLS DANCE',
 'CHINESE FROM THE NUTRCRACKER',
 'CHINESE VARIATION FROM THE NUTCRACKER SUITE',
 'CHRISTINE RICH STUDIO DANCE ACADEMY, IL',
 'CHRISTMAS MORNING',
 'CINDERELLA FAIRES',
 'CLARITY',
 'CLASS TANGO',
 'CLASSICAL BALLET ACADEMY, CO',
 'CLASSICAL BALLET ACADEMY, OR',
 'CLASSICAL BALLET CENTRE, SC',
 'CLASSICAL DANCE ACADEMY, CA',
 'CLASSICAL MINUET',
 'CLASSICAL PAS DE DEUX',
 'CLAY',
 'CLIFF',
 'CLOSING',
 'CLOUDS',
 'CLOUDSWALKERS',
 'COALESCE',
 'CODA FROM ESMERALDA',
 'COLLIDE',
 'COLORADO BALLET ACADEMY, CO',
 'COME HOME',
 'COME TO ME',
 'COMPLEX DESIRE',
 'CON FUERZA',
 'CONCERT DES FÉES',
 'CONCERTO',
 'CONCERTO 21',
 'CONCERTO FOR STRINGS',
 'CONCERTO IN D MINOR',
 'CONCERTO PER CHITARRA',
 'CONJURER',
 'CONSTANTINE',
 'CONTAGION',
 'CONTINUUM',
 'CONVERGENCE',
 'COPPELIA SPINNERS',
 'COPPELIA WEDDING PAS',
 'COPPELIA, PAS DE DEUX',
 'COPPELIA, THE DOLL',
 'CORANTE',
 'CORNELIUS, THE SELLER OF BALLOONS',
 'COSM',
 'COSMOS',
 'CREATION',
 'CRITICAL MOMENTS',
 'CUBA',
 'CUBA LINDA, CUBA HERMOSA...',
 'CUBICA',
 'CYGNETS',
 'D.Y.T.',
 'D4U',
 'DALLAS BALLET CENTER, TX',
 'DAMBALLAH WEDO',
 'DANCE ACADEMY OF LIBERTYVILLE, IL',
 'DANCE ARTS FL',
 'DANCE FOR FIVE',
 'DANCE FROM LA FILLE MAL GARDEE',
 'DANCE FROM WALPURGIS NIGHT',
 'DANCE INDUSTRY PERFORMING ARTS CENTER, TX',
 'DANCE INSTITUTE, TX',
 'DANCE OF THE BIG SWANS',
 'DANCE OF THE HOURS',
 'DANCE OF THE JEWELS',
 'DANCE OF THE MIRLETONS FROM THE NUTCRACKER',
 'DANCE OF THE REED PIPES',
 'DANCE STUDIO NO. 1',
 'DANCE WITH SWORDS, FROM GAYANEE',
 'DANCING ARTS CENTER, MA',
 'DANCING SHADOWS',
 'DANIELE',
 'DANSE BOHEME FROM CARMEN',
 'DANSE CHINOISE',
 'DANSE MANU FROM LA BAYADERE',
 'DANSE RUSSE',
 'DANZA DE TRADICION',
 'DARK CHARIOT',
 'DAUGHTERS OF ANN FRANK',
 'DAVID MATTHEW STUDIOS, MI',
 'DAYLIGHT',
 'DEADLY RIVALS',
 'DEBUT',
 'DECADANCE',
 'DEEP BLUE',
 'DEEP DOWN',
 'DEGAS',
 'DEGAS DANCE STUDIO',
 'DEGAS DANCE STUDIO, CA',
 'DEKOOZ',
 "DET'",
 'DIABLO ROJO',
 'DIAMOND DREAMZ',
 'DIANA',
 'DIANA EVANS SCHOOL OF DANCE, KY',
 'DISCORDIA AND MARS',
 'DISPLACEMENT',
 'DISSIDENT',
 'DISTRESS',
 'DIVERGENCE',
 'DIVERTISSEMENT',
 'DOEUN KIM 김도은',
 'DOLL HOUSE',
 'DOLLS',
 'DON QUIXOTE DANCE OF THE FLOWER SELLERS',
 'DON QUIXOTE,\xa0PAS DE DEUX',
 "DON'T WAIT",
 'DOWN A PATH',
 'DOWN THE LINE',
 'DOWN TO THE RIVER',
 'DREAM',
 'DREAM SCENE FROM DON QUIXOTE',
 'DREAMSCAPE',
 'DRIFTING MINDS',
 'DRINK THE SEA',
 'DRIVEN',
 'DRUMMING',
 'DUALIDADE',
 'DUALITY',
 'DUE',
 'DUELO',
 'DUERME AMOR MIO',
 'DUET',
 'DUO PAGANINI',
 'DUSK FIELDS',
 'DUST FROM STARS',
 'DÉJÀ VU',
 'E. GRIG NORWEGIAN DANCE',
 'EASE STREET',
 'EASY',
 'ECHO',
 'ECHOES',
 'ECLIPSE',
 'EDDY',
 'EDGE AND GRACE',
 'EDGED',
 'EL FUEGO',
 'EL TANGO DE ROXANNE',
 'ELEMENTS',
 'ELEVATOR',
 'ELITE CLASSICAL COACHING, TX',
 'ELLIPSIS',
 'EM BARALHO',
 'EMANATE',
 'EMERALD BALLET ACADEMY, WA',
 'EMOTION',
 'EMPTY',
 'ENCHANTING MATRIX',
 'ENCOUNTER',
 'ENCOUNTERS',
 'END GAME',
 'ENSEMBLE ARCANGELO',
 'ENTANGLES',
 'ENTRANCE',
 'ENTROPY',
 'ENVY',
 'ENYA',
 'EPAULEMENT',
 'ESHO RAS',
 'ESMERALDA AND FRIENDS',
 'ESMERALDA PAS DE QUATRE',
 "ESMERALDA'S FRIENDS",
 'ETERNAL',
 'ETOILE POLAIRE',
 'EVENSONG',
 'EVERY TIME WE SAY GOODBYE',
 'EVERYTHING MUST CHANGE',
 'EXCERPT FROM DON QUIXOTE',
 'EXCERPT FROM SWAN LAKE',
 'EXCERPT FROM WOLFGANG',
 'EXCERPTS FROM DECADANCE',
 'EXCERPTS FROM NAPOLI AND THE KERMESSE IN BRUGES',
 'EXCERPTS FROM ZACHACHA',
 'EXTREMITY',
 'EYES ON FIRE',
 'EЖИКИ',
 'FACETS',
 'FACTORY',
 'FAIRIES ADAGIO FROM SLEEPING BEAUTY',
 'FAIRY DANCE',
 'FAIRY DOLL',
 'FAIRY DOLL DUET',
 'FALL INTO ME',
 'FALLING ANGELS',
 'FALLING IN LOVE',
 'FALLING PETALS',
 'FAR AND AWAY',
 'FAREWELL',
 'FAUST',
 'FAWN',
 'FEATHERS AND WAX',
 'FELT',
 'FERVENT PRAYERS',
 'FIDDLER ON THE ROOF',
 'FIERCE SUN',
 'FIGARO',
 'FIGURES',
 'FIND THE WINDOW',
 'FINDING NEVERLAND',
 'FIRST TIME',
 'FIRST TIME EVER I SAW YOUR FACE',
 'FIVE GUYS NAMED MOE',
 'FIVES',
 'FLOCK',
 'FLOURISH',
 'FLY ME TO THE MOON',
 'FOLHAS SECAS',
 'FOLLOWING THE CONTOURS',
 'FOOTPRINTS',
 'FOR ALL',
 'FOR ALL DANCES',
 'FOR ALL ENSEMBLE',
 'FOR ALL ENSEMBLE NUMBERS',
 'FOR ALL ENSEMBLES',
 'FOR ALL ENSEMBLES OVERALL',
 'FOR ALL ENTRIES',
 'FOR ALL OF THEIR PIECES',
 'FOR ALL OF THEIR SMALL ENSEMBLE WORK',
 'FOR ALL OF THEIR WORK',
 'FOR ALL PIECES',
 'FOR ALL THEIR PIECES',
 'FOR ALL THEIR WORK',
 'FOR ALL WORK',
 'FOR THOSE WHO MOURN',
 'FORCE',
 'FORCE MARKER',
 'FORCED RETRO',
 'FORMÉS',
 'FORRÓ',
 'FORTUNA',
 'FOUND',
 'FRACTALS',
 'FRAGILE',
 'FRAGMENTED ONE',
 'FRAGMENTS OF A LANDSCAPE',
 'FREMD',
 'FRIDA',
 'FRIENDS',
 'FRIENDS DANCE FROM SLEEPING BEAUTY',
 'FRIENDS OF COPPELIA',
 'FRIENDS OF GISELLE',
 'FRIENDSHIP',
 'FROZEN',
 'FRÄULEIN TÄNZE',
 'FUEGO',
 'FUNERAL',
 'GAME OF SHADOWS',
 'GARDEN',
 'GARGOYLES',
 'GARLAND WALTZ FROM SLEEPING BEAUTY',
 'GATED',
 'GATHERING MASS',
 'GENTLY FALLING, FLOATING DOWN',
 'GEORGIAN DANCE',
 'GHOST',
 'GHOST LIGHTS',
 'GIDDY',
 'GINA CHOI 최기나',
 'GIRLS OF THE 40',
 'GISELLE',
 'GISELLE, PEASANT PAS DE DEUX ACT I',
 'GLORIANTUR',
 'GO BRAVE',
 'GO GIRLS',
 'GODSPEED',
 'GOLIGHTLY',
 'GONE WITH A WIND',
 'GONGFU',
 'GOPAK',
 'GOTTSCHALK: WORKS FOR PIANO OPUS 2',
 "GOUNOD'S WALTZ",
 'GRADUALLY',
 'GRAND AVENUE BLUES',
 'GRAND PAS CLASSIQUE PAS DE DEUX',
 'GRAND PAS CLASSIQUE – PAS DE DEUX',
 'GRAND PAS DE QUATRE',
 'GRAND PAS DES EVENTAILS',
 'GRAND PAS DES FLEURS',
 'GRAND PAS ESPAGNOL',
 'GRAND STAND',
 'GRANDE TARANTELLA',
 'GRANDE VALSE',
 'GRAVITATE',
 'GREAT ARE YOU LORD',
 'GREENWICH BALLET ACADEMY, CT',
 'GUARDIANS',
 'GYPSY DANCE',
 'HAKA',
 'HALCYON',
 'HANAMACHI',
 'HAPPINESS DOES NOT WAIT',
 'HAPPY END',
 'HAPPY GIRLS!',
 'HARLEQUINADE PAS DE DEUX',
 'HARLEQUINADE PAS DE DEUX AND CODA',
 'HARLEQUINADE, PAS DE DEUX',
 'HARLEQUINADE\xa0 PAS DE DEUX',
 'HARVEST VARIATION FROM COPPELIA',
 'HAVA NAGILA',
 'HEAD ABOVE WATER',
 'HEART OF GLASS',
 'HEART OF STONE',
 'HEARTBEAT',
 'HELP OF THE HELPLESS',
 'HER OFFICE',
 'HHB 101',
 'HIGH TIDE',
 'HIVE',
 'HOLBERG SUITE',
 'HOLDING ON/LETTING GO',
 'HOME',
 'HOMETOWN',
 'HOPAK',
 'HOPAK DITY',
 'HOPE',
 'HOPELESS WANDERER',
 'HOSPITAL',
 'HOSPITAL BEDS',
 'HOW IT ENDS',
 'HOW TO FLY',
 'HOW WILL I KNOW',
 'HOWARD W. BLAKE HIGH SCHOOL FOR THE PERFORMING ARTS FL',
 'HOWARD W. BLAKE HIGH SCHOOL, FL',
 'HUAPANGO',
 'HUMAN',
 'HUMANITY',
 'HUNGER',
 'HUNGERIAN DANCE',
 'HUNTINGTON BEACH ACADEMY FOR THE PERFORMING ARTS',
 'HURTS',
 'HUTSUL',
 'HYEWON KANG 강혜원',
 'I LIE',
 "I'LL TRADE YOUR BROKEN WINGS FOR MINE",
 "I'M GOING HOME",
 'ICE AIR WIND WATER',
 'ICTUS',
 'IDIOSYNCRATIC RISING',
 'IF',
 'IL RIPOSO',
 'ILLINOIS DANCE CONSERVATORY, IL',
 'ILLUMINATION',
 'IMMA SHINE',
 'IMMENSITIES',
 'IMPACT',
 'IMPACT DANCE OF ATLANTA, GA',
 'IMPROMPTU',
 'IN A DANCE STUDIO',
 'IN BETWEEN',
 'IN HARMONY',
 'IN MY DREAM',
 'IN SOUNG',
 'IN THE LIGHT OF THE MOON',
 'INCANTO',
 'INCEPTION',
 'INDIANA BALLET CONSERVATORY, IL',
 'INDIANA BALLET CONSERVATORY, IN',
 'INDUSTRIAL',
 'INERTIA',
 'INFINITUM',
 'INFLECTION',
 'INFLUX',
 'INFRA',
 'INLAND PACIFIC BALLET ACADEMY, CA',
 'INNOCENCE',
 'INSIGHT',
 'INSOMNIA',
 'INSPIRE DANCE CENTRE, OR',
 'INTEGRAL SILENCE',
 'INTEGRATION',
 'INTERCONNECT',
 'INTERIOR ECOLOGY',
 'INTERNATIONAL BALLET ACADEMY, NC',
 'INTERNATIONAL BALLET THEATER ACADEMY, PA',
 'INTO THE TREES',
 'INTREPID',
 'INTREPID INTERNATIONAL EVER I SAW YOUR FACE',
 'INTREPID LOVE',
 'INVASION',
 'INVERSE',
 'INVITATION',
 'IRON',
 'IS IT ME?',
 'IT STARTS WITH US',
 "IT'S MINE",
 "IT'S YOU....INTERTWINED",
 'ITALIAN CONCERTO 3RD MOVEMENT',
 'IV',
 'JACK',
 "JACQUELINE'S SCHOOL OF BALLET, UT",
 'JAEMYEONG JANG 장재명',
 'JAMES BOND',
 'JANGGU FESTIVAL',
 'JASMINE',
 'JASMINE FLOWER',
 'JESU, JOY!',
 'JEWELS',
 'JEWISH DANCE',
 'JIG',
 'JIHYEONG CHOI 최지형',
 'JILL',
 'JIOH KIM 김지오',
 'JIYOUNG KIM 김지영',
 'JIYU KWON 권지유',
 'JOTA',
 'JOTA DE ARAGON',
 'JOY OF SPRING',
 'JUBILEE POLKA',
 'JUMYEONG JANG 장주명',
 'JUNIOR ALLEGRO',
 'JUST ANOTHER DAY',
 'JUST YOU AND ME',
 'K-BALLET ART, LADANSE BALLET, BLUET BALLET ACADEMY, EWHA BALLET ETOILE, YONGTONG E-WHA BALLET ACADEMY, KIM HYE YOUNG BALLET ACADEMY, LEE WONJU BALLET ACADEMY, JS BALLET, POSE BALLET ACADEMY, S.M. BALLET',
 'KALEIDOSCOPE',
 'KAMUI',
 'KARMA: UNIVERSAL LAW',
 'KARMIC VARIATIONS',
 'KBEC BALLET ACADEMY',
 'KINA',
 'KINETIC',
 "KITRI'S DUET",
 'KOI-TET',
 'KOLTUN BALLET BOSTON, MA',
 'KOZACHOK',
 'KYRIE',
 'LA BAYADERE',
 'LA BAYADERE PAS DE TROIS',
 'LA BAYADERE THREE SHADES',
 'LA CAMPANELLA',
 'LA CHASSE (THE CHASE)',
 'LA DANSE DES ENFANTS',
 'LA ESMERALDA PAS DE DEUX',
 'LA FILLE FRIENDS',
 'LA FILLE MAL GARDEE',
 'LA FILLE MAL GARDEE DUET',
 'LA FILLE MAL GARDEE PAS DE DEUX',
 'LA FORCE',
 'LA PORTA',
 'LA RICETTA DI CICIRNELLA',
 'LA SOIREE',
 'LA VENTANA SELECTIONS',
 'LAMENT',
 'LASCIATO IL GIOCOO',
 'LAST MOMENT',
 'LE CORSAIRE - ODALISQUE',
 'LE CORSAIRE PAS DE DEUX',
 'LE CORSAIRE PAS DE DEUX AND CODA',
 'LE CORSAIRE PAS DE TROIS',
 'LE CORSAIRE, ACT III PAS DE DEUX',
 'LE CORSAIRE-LE JARDIN ANIMÉ',
 'LE JARDIN DE ANIMEE',
 'LEGION',
 'LES PETITS RATS',
 'LET IT BE',
 'LETTERS OF A TRAVELER',
 'LETTING GO',
 'LEZGINKA',
 'LEZGINKA (WARRIOR DANCE)',
 'LIBERARE',
 'LIBERATE',
 'LIBERTANGO',
 'LIFE',
 'LIKE A PRAYER',
 'LITTLE HOOLIGANS',
 'LITTLE SKELETONS',
 'LITTLETON BALLET ACADEMY, CO',
 'LOCKED UP',
 'LOOK',
 'LOOK OUT',
 'LOOKING BACK, GOING FORWARDS',
 'LOS ANGELES BALLET ACADEMY, CA',
 'LOST ANGEL',
 'LOUDER THAN WORDS',
 'LOVE AFTER LOVE',
 'LOVE BOI',
 'LUNA SUITES',
 'LYRICAL MINUET',
 'M2S1',
 'MAESTOSO',
 'MAESTRO',
 'MAGALENHA',
 'MAGNUS',
 'MAIDS OF HONOR',
 'MAIN STREET BALLET COMPANY, IL',
 'MANGROVES',
 'MANNEQUIN',
 'MANU',
 'MAPLE LEAF RAG',
 'MARAT DAUKAYEV SCHOOL OF BALLET',
 'MARINA ALMAYEVA SCHOOL OF CLASSICAL BALLET, TX',
 'MARINHEIRAS',
 'MARK MY WORDS',
 'MARK YOUR MOVE',
 'MARZIPAN FROM THE NUTCRACKER',
 'MASQUERADE',
 'MATROYSHKA',
 'MATRYOSHKI',
 'MAZURKA FROM COPELLIA',
 'MEA CULPA',
 'MEMOIRS OF VERONICA AND VINCENT',
 'MEMORIES',
 'MEMORIES DE FUTUR',
 'METAMORPHOSIS',
 'METAMORPHOSIS TWO',
 'METRIC',
 'METROPOLITAN SCHOOL OF THE ARTS ACADEMY, VA',
 'MI',
 'MICHAEL MEETS MOZART',
 'MIDAS TOUCH',
 'MIDNIGHT',
 'MILENBERG JOYS',
 'MINKUS SUITE',
 'MIRLETONS FROM THE NUTCRACKER',
 'MIRLITONS DANCE FROM THE NUTCRACKER',
 'MIRROR, MIRROR',
 'MIST',
 'MIST OF A DREAM',
 'MOGA CONSERVATORY OF DANCE, UT',
 'MOLECULES',
 'MOMENTS CAPTURED',
 'MOMENTS CAPTURED IN TIME',
 'MONOCHROME',
 'MOONLIGHT SONATA',
 'MORIAKY (SAILORS)',
 'MORNING STAR DANCE ACADEMY OF ATLANTA, GA',
 'MOSCOVIAN KADRIL',
 'MOVE ON',
 'MOVEMENT',
 'MOVEMENT FOR 7',
 'MOVING ON',
 'MOZART',
 "MOZART'S REQUIEM",
 'MOZART/SPELL',
 'MO·ZAR·TIF',
 'MUFFLED',
 'MUTATION',
 'MUTE',
 'MV DANCE',
 'MY BEAUTIFUL DARK',
 'MY HEART HAS FOUR CORNERS',
 'MY IMMORTAL',
 'MY LIFE FOR YOURS',
 'MY SOUL IS NOT STRIPED',
 'MY UKRAINE',
 'MYTH AND THE VOID',
 'MYTH OF THE MUSIC BOX',
 'NATURE BOY',
 'NAYEON KIM 김나연',
 'NE ME QUITTE PAS',
 'NEBULA',
 'NEBULOUS',
 'NEGATIVE SPACE',
 'NESTING',
 'NEW YEAR',
 'NEXT GENERATION BALLET AT THE PATEL CONSERVATORY FL',
 'NEXUS',
 'NIGHT',
 'NIGHT RUN',
 'NO FEAR',
 'NO NO NO',
 'NO SURRENDER',
 'NOCTURNE',
 'NOIR ET BLANC',
 'NORTH COUNTY ACADEMY OF DANCE, CA',
 'NORTHPOINTE DANCE ACADEMY, OH',
 'NORWEGIAN DANCE',
 'NOSTALGIA',
 'NOT HOW IT SEEMS',
 'NOT IN THAT WAY',
 'NOTHINGNESS',
 'NOWHERE TOGETHER',
 'NUEVO SCHOOL OF CONTEMPORARY BALLET',
 'NUMBERS',
 'NURI PARK 박누리',
 'NY, NY',
 'NYMPHS',
 'NYMPHS FROM THE BALLET WALPURGIS NIGHT',
 'O QUIE EU NAO POSSO SENTIR',
 'O RAPAZ APAIXONADO',
 'OCEAN',
 'OCEAN AND PEARLS',
 'OCEAN AND PEARLS FROM "THE LITTLE HUMPBACKED HORSE',
 'OCEANS',
 'OCEANS AND PEARLS',
 'OCEANS AND PEARLS FROM LITTLE HUMPBACKED HORSE',
 'ODALISQUE',
 'ODALISQUE ADAGIO',
 'ODALISQUE FROM LE CORSAIRE',
 'ODALISQUE PAS DE TROIS',
 'ODALISQUE PAS DE TROIS FROM LE CORSAIRE',
 'ODALISQUE TRIO FROM LE CORSAIR',
 'ODALISQUE TRIO FROM LE CORSAIRE',
 'ODALISQUES',
 'ODALISQUES FROM LE CORSAIRE',
 'ODONATA',
 'OH WHAT A WORLD',
 'OLD SKIN',
 'OMAGGIO A ROSSINI',
 'OMNI',
 'ON BOARD',
 'ON CUE',
 'ON MY WAY…..',
 'ON THEN AND NOW',
 'ONE STEP INSIDE',
 'ONE TOO MANY',
 'ORANGE GROVE MAGNET MIDDLE SCHOOL FL',
 'ORBIT',
 'ORIGEM',
 'ORIGINAL DON',
 'ORLANDO BALLET SCHOOL FL',
 'OS CAÇADORES',
 'OSSETIAN CHARACTER DANCE',
 'OUT OF BREATH',
 'OUT OF THE SUN',
 'OUTLANDS',
 'OUTONAL',
 'OUTRE',
 'OUTSIDER',
 'OVER AND AGAIN',
 'OVERCOME',
 'OVERCOMING DARKNESS',
 'OYSTER',
 "PABLO'S DISASTERPIECW",
 'PACE',
 'PALLADIO',
 'PAMIRSKII DANCE',
 'PANGAEA',
 "PAQUITA'S PALS",
 'PARADIGM',
 'PARADOX',
 'PARTICLES',
 'PARTITA',
 'PAS CLASSIQUE',
 'PAS DE CINQ',
 'PAS DE DEUX FROM CAVALRY HALT',
 'PAS DE DEUX FROM COPPELIA',
 'PAS DE DEUX FROM DIANA AND ACTEON',
 'PAS DE DEUX FROM DON QUIXOTE',
 'PAS DE DEUX FROM DON QUIXOTE AND PAS DE DEUX FROM COPPELIA',
 'PAS DE DEUX FROM FLAMES OF PARIS',
 'PAS DE DEUX FROM FLOWER FESTIVAL AT GENZANO',
 'PAS DE DEUX FROM FLOWER FESTIVAL AT GENZANO, CA',
 'PAS DE DEUX FROM FLOWER FESTIVAL IN GENZANO',
 'PAS DE DEUX FROM GISELLE',
 'PAS DE DEUX FROM GRAND PAS CLASSIQUE',
 'PAS DE DEUX FROM HARLEQUINADE',
 'PAS DE DEUX FROM LA FILLE MAL GARDEE',
 'PAS DE DEUX FROM LA FILLE MAL GARDÉE',
 'PAS DE DEUX FROM LE CORSAIRE',
 'PAS DE DEUX FROM LE FILLE MAL GARDEE',
 'PAS DE DEUX FROM SATANELLA',
 'PAS DE DEUX FROM SLEEPING BEAUTY',
 'PAS DE DEUX FROM SPARTACUS',
 'PAS DE DEUX FROM SWAN LAKE',
 'PAS DE DEUX FROM THE NUTCRACKER',
 'PAS DE DEUX FROM THE SUGAR PLUM FAIRY',
 'PAS DE DEUX FROM WILLIAM TELL',
 'PAS DE SIX FROM THE POLAR EXPRESS',
 'PAS DE TROIS',
 'PAS DE TROIS DES ODALISQUES',
 'PAS DE TROIS FROM FAIRY DOLL',
 'PAS DE TROIS FROM LA BAYADERE',
 'PAS DE TROIS FROM MIRLETONS',
 'PAS DE TROIS FROM NUTCRACKER',
 'PAS DE TROIS FROM SWAN LAKE',
 'PAS DE TROIS NUTCRACKER',
 'PAS ESPANHOL',
 'PASSAGE',
 'PATH 5',
 'PEACE BENEATH',
 'PEACE NO VIOLENCE',
 'PEACOCK DANCE',
 'PEARLS',
 'PEARLS VARIATION',
 'PEARLS VARIATION FROM THE LITTLE HUMPBACK HORSE',
 'PEARLS VARIATION FROM THE LITTLE HUMPBACKED HORSE',
 'PEASANT DANCE',
 'PEASANT PAS DE DEUX FROM GISELLE',
 'PEER GYNT',
 'PEIXINHOS',
 'PENNY LANE',
 'PENROSE',
 'PEOPLE HELP THE PEOPLE',
 'PERIPLACE',
 'PERPETUO',
 'PERPETUUM',
 'PERSERVERANCE',
 'PERTH',
 'PETIT PARIS',
 'PETITE QUARTET',
 'PETITE SEAT',
 'PETITE SYLPHS',
 'PETRUSHKA',
 'PHANTOM OF THE OPERA',
 'PHASES OF RENEWAL',
 'PHOENIX',
 'PIANO CONCERTO',
 'PIAZOLA',
 'PIAZOLLA',
 'PIZZCATO POLKA',
 'PIZZICATO',
 'PIZZICATO DUET FROM SYLVIA',
 'PIZZICATTO',
 'PLYASOVAYA',
 'POINTELESS',
 'POLARIZED',
 'PONTO DO INTERCECCION',
 'POPS ON THE PRAIRIE',
 'POSSIBLE',
 'POUR TOI, MARCEAU',
 'PRECIOUS STONES',
 'PREDATOR',
 'PRELUDE',
 'PREMIERE BALLET ACADEMY, TX',
 'PRESSLUFHAMMER',
 'PRESSLUFTHAMMER',
 'PRIMAVERA PORTENA',
 'PRISION OF DECISION',
 'PRISMATIC',
 'PROKOFIEV PART 2',
 'PROMENADE',
 'PROMETHEUS',
 'PROSERPINA',
 'PRUITT IGOE',
 'PULCINELLA SUITE',
 'PULSE',
 'PUPPETS LIFE',
 'PURGATORY',
 'PUSHING FORWARD TOGETHER',
 "PUSSIN' BOOTS",
 'QUATRE',
 'QUIET NOW',
 'QUIET SEASON',
 'QUIZAS',
 'RAEIN',
 'RAGING CHI',
 'RAIN',
 'RAINDROPS',
 'RAMOS VERDÉ',
 'RASTA LA VISTA',
 'RAYMONDA-ARABIAN',
 'REBORN',
 'RECESS',
 'RECOMPOSED WINTER',
 'RED RIDING HOOD',
 'REFLECTION',
 'REFLECTIONS',
 'REFLECTIONS ON IRMA',
 'REFUGE',
 'REGINA DI SABA',
 'REJOICE',
 'RELAX',
 'RELEASED',
 'REMEMBRANCE',
 'REMEMBRANCE OF A LOST EARTH',
 'RENASCER DA FENIX',
 'RENNER BALLET ACADEMY, NC',

In [57]:
sorted(dancers[dancers["Dance Category"].str.contains("PAS DE DEUX", na=False)].Name.unique())

['(11)',
 '(13)',
 '(14)',
 '(15)',
 '(16)',
 '(18)',
 '(9)',
 'ACTEON, PAS DE DEUX',
 'AFONSO FERREIRA (12), (LA FILLE MAL GARDEE)',
 'AFTERMATH',
 'ALBERTO GIL (13), (HARLEQUINADE)',
 'ALECSIA LAZARESCU',
 'ALEGRE',
 'ALESSANDRO FROLA, 12, MARTINA MANTOVANI, 13',
 'ALICE PELIZZA',
 'ALL PAS DE DEUX',
 'ALL THAT WAS LEFT',
 'ALLEGRO APPASSIONATO',
 'ANA COSTEIRA',
 'ANA FRANCISCA CRUZ',
 'ANA LUISA ARANTES NEGRAO',
 'ANA NOVAIS',
 'ANTÓNIO CASALINHO (16), (FLAMES OF PARIS',
 'AO WANG (17), LANG MA (19)',
 'ARE YOU GOING...?',
 'ARTHUR WILLIE (FLOWER FESTIVAL IN GENZANO)',
 'ASIER BAUTISTA (11), (SATANELLA)',
 'BACH PAS DE DEUX',
 'BEFORE I GO',
 'BEGIN THE BEGUINE',
 'BELLA KIRBY (11), AUSTEN ACEVEDO (13)',
 'BLUE BIRD PAS DE DEUX FROM SLEEPING BEAUTY',
 'BLUEBIRD PAS DE DEUX FROM SLEEPING BEAUTY',
 'BOYOUNG KIM 김보영',
 'BRIANNA BERRIOS (13), BLAKE KESSLER (14)',
 'BRUSH',
 'CAPULET',
 'CLAIRE RATHRUN (18), RAMMARU SHINDO (21)',
 'CLASSICAL BALLET OF WNY, NY',
 'COACTION AND CRANK HANDLE',
 'COME HOME',
 'COPPELIA',
 'COPPELIA PAS DE DEUX',
 'COPPELIA, PAS DE DEUX',
 'COURTNEY GUNSTEEN (13), TANNER BLECK (14)',
 'COVET',
 'D4U',
 'DAME À LA LAVANDE',
 'DAWN',
 'DIANA',
 'DIANA AND ACTEON PDD',
 'DIOGO BETENCOURT, (SATANELLA)',
 'DISTURBANCE WITH A SINGULAR APPROACH',
 'DIVERGANCE',
 'DOEUN KIM 김도은',
 'DON QUIXOTE',
 'DON QUIXOTE PDD',
 'DON QUIXOTE,\xa0PAS DE DEUX',
 'EBO',
 'EDERLEZI',
 'EMBERS',
 'ENCHANTED MATRIX',
 'EVAPORATE',
 'EXIT',
 'FELIX BOBOI (14), (COPPELIA)',
 'FERROMAGNETISM',
 'FIRE',
 'FLAMES OF PARIS',
 'FLAMES OF PARIS, BASQUES DANCE',
 'FLOWER FESTIVAL IN GENZANO',
 'FLOWER FESTIVAL IN GENZANO, PAS DE DEUX',
 'FOR ALL PAS DE DEUX',
 'FOR ALL PAS DE DUEX',
 'FOR ALL PDD',
 'FORBIDDEN LOVE',
 'FOUND FIT',
 "FRANCISCO GOMES (16), (LE CORSAIRE, PAS D'ESCLAVE)",
 'FRESH',
 'FROST',
 'GABRIELLA STILO (13), BRANDON CARPIO (15)',
 'GABRIELLA STILO (14), FRANCISCO SERRANO (14)',
 'GAYEON JUNG, (19), KIMIN KIM (19)',
 'GINA CHOI 최기나',
 'GIOVANNA DE SOUZA GOMES',
 'GISELLE, PEASANT PAS DE DEUX ACT I',
 'GRAND PAS CLASSIQUE PAS DE DEUX',
 'GRAND PAS CLASSIQUE\xa0 PAS DE DEUX',
 'GRAND PAS CLASSIQUE\xa0PAS DE DEUX',
 'GYMNOPEDIE',
 "HAPPY NEW YEAR'S DAY",
 'HARLEQUINADE',
 'HARLEQUINADE PAS DE DEUX',
 'HARLEQUINADE PAS DE DEUX AND CODA',
 'HARLEQUINADE PDD',
 'HARLEQUINADE\xa0 PAS DE DEUX',
 'HARLEQUINADE\xa0PAS DE DEUX',
 'HARLEQUINADE\xa0PAS DE DEUX AND DIANA',
 'HARMONY',
 'HOPAK DITY',
 'HUNTER',
 'HUNTER AND MEDITATION (KIARRA WAIDELICH, DARRION SELLMAN)',
 'HYEWON KANG 강혜원',
 'I WISH YOU LOVE',
 'IN THE BEGINNING',
 'IN THE VOID',
 'INFINITY',
 'INGRATA',
 'INTERTWINED',
 'INTERWOVEN',
 'IVAN MALAGUTI (12), (14)',
 'IVAN MALAGUTI (12), (HARLEQUINADE)',
 'JAEMYEONG JANG 장재명',
 'JESSICA HE (16), ANDRES ZUNIGA (16)',
 'JIHYEONG CHOI 최지형',
 'JIOH KIM 김지오',
 'JIYOUNG KIM 김지영',
 'JIYU KWON 권지유',
 'JOAO FELIPE SANTANA (CARNIVAL IN VENICE)',
 'JULIETTE BOSCO (12), THEOPHILUS PILETTE (15)',
 'JUMYEONG JANG 장주명',
 'JUST YOU AND ME',
 'KENEDY KALLAS (14), AUSTEN ACEVEDO (15)',
 "L'ULTIMO BACIO",
 'LA BAYADERE PAS DE DEUX',
 'LA ESMERALDA PAS DE DEUX',
 'LA FAVORITA',
 'LA FILLE MAL GARDEE',
 'LA FILLE MAL GARDEE PAS DE DEUX',
 'LA SYLPHIDE',
 'LA SYLPHIDE PAS DE DEUX',
 'LA SYLPHIDE)',
 'LA VIE EN ROSE',
 'LAND',
 'LAURENCIA PAS DE DEUX',
 'LE CORSAIRE',
 'LE CORSAIRE, ACT III',
 'LE CORSAIRE, ACT III PAS DE DEUX',
 'LE CORSAIRE, ACT III PDD',
 'LE MANTEAU ROUGE',
 'LEAN ON',
 'LETTERS',
 'LEZGINKA',
 'LOVE (2)',
 'LUMINOUS',
 'MAD MOZART',
 'MADELEINE GARDELLA (16), PETER WEIL (18)',
 'MADNESS',
 'MAGGIE CHADBOURNE (13), ROBERTO BARQUI (16)',
 'MAKSIM APATONOV, (THE SLEEPING BEAUTY GRAND PAS ACT III)',
 'MARCHE MINATURE',
 'MARGARIDA GONÇALVES',
 'MARGARITA FERNANDES',
 'MARIA CLARA COELHO (13), DAVI CHAGAS (16)',
 'MARTINA VANZETTO',
 'MATTEO FOGLI (17), (18)',
 'MATTEO FOGLI (17), (SATANELLA)',
 'MAYA CRISTINA CIOBOTA',
 'MERLITONS DANCE FROM THE NUTCRACKER',
 'MICHELA CAPRARULO',
 'MICHELLE',
 'MO CEN ZHAO (15) ZACHAY DOWNER (17)',
 'MONSTER',
 'MY REFUGE',
 'NATTALIA TIEMI',
 'NAYEON KIM 김나연',
 'NEAPOLITAN DANCE',
 'NEAR LIGHT',
 'NICOLE FANNEY (13), PRESTON CHAMBLEE (17)',
 'NINA MIRÓ VERGER',
 'NO REGRETS',
 'NORA CLEMENTE, 16, BRYCE LEE, 16',
 'NOSALTRES',
 'NUIT BLANCHE',
 'NURI PARK 박누리',
 'O MEU PRIMEIRO AMOR',
 'ODALISQUE PAS DE TROIS',
 'OLHO NU',
 'ONCE UPON A TIME',
 'PAS DE DEUX FROM COPPELIA',
 'PAS DE DEUX FROM FLOWER FESTIVAL IN GENZANO',
 'PAS DE DEUX FROM GISELLE',
 'PAS DE DEUX FROM GRAND PAS CLASSIQUE',
 'PAS DE DEUX FROM GRAND PAS CLASSQUE',
 'PAS DE DEUX FROM HARLIQUENADE',
 'PAS DE DEUX FROM LA BAYADERE',
 'PAS DE DEUX FROM LA ESMERALDA',
 'PAS DE DEUX FROM LA SYLPHIDE',
 'PAS DE DEUX FROM LES SYLPHIDE',
 'PAS DE DEUX FROM SWAN LAKE',
 'PAS DE DEUX FROM THE FLAMES OF PARIS',
 'PAS DE DEUX FROM THE NUTCRACKER',
 'PAS DE TRIO',
 'PEASANAT PAS DE DEUX FROM GISELLE',
 'PENELOPE IOANNOU (15), MAX MUKHAMEDOV (18)',
 'PERCEPTION',
 'PETER CAUA SILVA (HARLEQUINADE)',
 'PRESAGE',
 'PRIMO DUETTO',
 'QUARTER NOTE',
 'QUIET SEASON',
 'QUIZAS',
 'RACHEL QUINTAO',
 'REMEMBER',
 'REMEMBERANCE',
 "REMY D'ORNAY",
 'RICCARDO GIORGIO GREGOLIN (16), (THE CAVALRY HALT)',
 'RICCARDO UMBERTO BRUTTOMESSO (17), (15)',
 'RICCARDO UMBERTO BRUTTOMESSO (17), (MOSZKOVSKY WALTZ)',
 'SARA MASTROGIOVANNI',
 'SARAJEVO',
 'SATANELLA PAS DE DEUX',
 'SEOHYUN KIM 김서현',
 'SEOYEON JEONG 정서연',
 'SEQUENCE',
 'SERENA SOVDSNES (15), JULIO MEDEROS (24)',
 'SEUNG YEONG YANG (15), SUNWOO LEE (17)',
 'SHE LIES',
 'SHIJEAN KIM 김시진',
 'SHOKO KITAGUCHI BALLET STUDIO, JAPAN',
 'SIHU BAN 반시후',
 'SIWOO JEONG 정시우',
 'SLAVE, LE CORSAIRE',
 'SLEEPING BEAUTY',
 'SOLDGER',
 'SOMEWHERE IN TIME',
 'SOMMERDANCE',
 'SPACE TO BLOOM',
 'SPECIES DISTURBED',
 "SPIEGEL I'M SPIEGEL",
 'STAY CLOSE',
 'STILL IN YOUR SILENCE',
 'STRAUSS GALOP',
 'SUNGMIN KIM 김성민',
 'SUNGYEON HONG 홍성연',
 'SUSPICION',
 'SWAN LAKE BLACK SWAN PAS DE DEUX ACT III',
 'SYMPHONNIC',
 'TATE RAE (11), LAZARO MORALES (12)',
 'THE CAVALRY HALT\xa0PAS DE DEUX',
 'THE CORONATION',
 'THE FLAMES OF PARIS',
 'THE FLAMES OF PARIS PAS DE DEUX',
 'THE FLAMES OF PARIS PDD',
 'THE GOLDEN AGE',
 'THE LEGEND OF LOVE',
 'THE LOUDEST LACK OF BREATHING',
 'THE NUTCRACKER SUITE PAS DE DEUX',
 'THE PATH',
 'THE REVELATION',
 'THE SLEEPING BEAUTY',
 'THE SLEEPING BEAUTY BLUEBIRD PAS DE DEUX',
 'THE SLEEPING BEAUTY GRAND PAS DE DEUX ACT III',
 'THE TALISMAN PAS DE DEUX',
 'TI-TA',
 'TICK TAK',
 'TINTAL',
 'TOMAS RUAO, (LA BAYADERE)',
 'TWIN',
 'TWO',
 'ULIANA EFIMOVA',
 'UN DIMANCHE APRÉS-MIDI',
 'UNCHAINED',
 'UNREQUITED',
 'US',
 'VALENTINA LEALI, MASSIMO SONZOGNI',
 'VICENTE INCENTIV',
 'VICTORIA WONG (15), CHANDLER PROCTOR (17)',
 'VICTORIA WONG(15), CHANDLER PROCTOR (17)',
 'VITOR AUGUSTO VAZ (HARLEQUINADE)',
 'VIVALDI PAS DE DUEX',
 'WALC',
 'WALLFLOWER',
 'WE ARE DANCING PERGOLSI',
 'WENYU GUO (19), STEFAN GONCALVEZ (19)',
 "WHAT I'VE DONE",
 'WHEN IT IS TIME',
 'WITHIN',
 'WONA PARK (15), JIN SOL EUM (18)',
 'WOULD YOU GO OUT WITH ME TONIGHT',
 'YE LIM CHOI (19), SUN WOO LEE (18)',
 'YUNJIN BAE 배윤진',
 'À DEUX']

In [52]:
d = dancers[dancers["Dance Category"].str.contains("ENSEMBLES & PAS DE DEUX", na=False)].Name.unique()
print(d)

dance_pattern = re.compile(r'^[^가-힣]+$') # keep anything that does NOT contain Korean characters
d = [x for x in d if dance_pattern.match(x)]

dances += d
d

['JIOH KIM 김지오' 'SIWOO JEONG 정시우' 'YUNJIN BAE 배윤진' 'JUMYEONG JANG 장주명'
 'JAEMYEONG JANG 장재명' 'SUNGYEON HONG 홍성연' 'SHIJEAN KIM 김시진'
 'SEOHYUN KIM 김서현' 'SEOYEON JEONG 정서연' 'GINA CHOI 최기나' 'NURI PARK 박누리'
 'SIHU BAN 반시후' 'HYEWON KANG 강혜원' 'SUNGMIN KIM 김성민' 'DOEUN KIM 김도은'
 'NAYEON KIM 김나연' 'BOYOUNG KIM 김보영' 'JIHYEONG CHOI 최지형' 'JIYOUNG KIM 김지영'
 'JIYU KWON 권지유' 'ALL ENSEMBLES' 'NOWHERE TOGETHER' 'WHISPER IN MY EAR']

['ALL ENSEMBLES', 'NOWHERE TOGETHER', 'WHISPER IN MY EAR']

In [53]:
dances += list(dancers[dancers["Dance Category"].str.contains(r"LARGE ENSEMBLES|SMALL ENSEMBLES|DUETS & PAS DE DEUX|DUET/TRIO", na=False)].Name)

In [54]:
dances = np.sort(np.unique(dances))
# dances

# Final Dancers data:

In [55]:
# name_instances = winners.Name_resolved.value_counts().to_dict()

In [56]:
dancers = dancers[
    (~dancers.Name.isin(dances))
]

dancers

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category,Names_resolved
6,"KORY GLATMAN, NJ",NaN,2000,"WASHINGTON, DC",3RD PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,[KORY GLATMAN]
7,ASHTON BERKLEY,"THE KIROV ACADEMY, DC",2000,"WASHINGTON, DC",2ND PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,NaN
8,DANA GAULE,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",1ST PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,NaN
9,KATRINA DALTON,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",HOPE AWARD,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,NaN
10,TIFFANY SMITH,"HARRISBUG DANCE CONSERVATORY, PA",2000,"WASHINGTON, DC",3RD PLACE (TIE),JUNIOR AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
43499,THE LAKE,"THE DANCE CENTER (TDC), CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"THE DANCE CENTER (TDC), CA",SMALL ENSEMBLES,NaN,NaN
43500,THE ORBITS,"EVA DANCE ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"EVA DANCE ACADEMY, CA",SMALL ENSEMBLES,NaN,NaN
43501,WITHOUT YOU,"JUN LU PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"JUN LU PERFORMING ARTS, CA",SMALL ENSEMBLES,NaN,NaN
43518,KIRA FARGAS,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN
43519,HADASSAH PERRY,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN