# Imports and data:

In [1]:
import pandas as pd
import numpy as np
import regex as re
from rapidfuzz import process, fuzz

In [2]:
%run classify_names

In [3]:
w1 = pd.read_excel("data/WINNERS 2000-2010 - 05.xlsx")
w2 = pd.read_excel("data/WINNERS 2011-2020 - 05.xlsx")
w3 = pd.read_excel("data/WINNERS 2021-2025 - 05.xlsx")
w4 = pd.read_excel("data/WINNERS 2026-2030 - 05.xlsx")

In [4]:
winners = pd.concat([w1, w2, w3, w4], ignore_index=True)

winners.shape

(43457, 10)

In [5]:
winners.dtypes

Name                   object
School                 object
Year                    int64
City                   object
Award                  object
Division               object
Category               object
School / Company       object
Division / Position    object
Dance Category         object
dtype: object

In [6]:
winners

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
0,NaN,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
1,NaN,"The Kirov Academy, DC",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
2,8+3,Inwood Dance Company,2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
3,Cabaret,"Dance Conservatory, DE",2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
4,Make Them Hear You,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",2nd Place,NaN,Ensembles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
43452,Dance For Six,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43453,Coppelia Friends Dance,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43454,Kira Fargas,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43455,Hadassah Perry,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43456,NaN,NaN,2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

In [7]:
# for s in winners.School.value_counts().index:
#     print(s)

In [8]:
# for a in winners["Award"].value_counts().index:
#     print(a)

In [9]:
winners["Division"].value_counts()

Division
Senior Age Division             2837
Junior Age Division             2604
Pre-Competitive Age Division    1102
Top 12 - Senior Age Division       1
Name: count, dtype: int64

In [10]:
winners["Category"].value_counts()

Category
Classical Dance Category                   2909
Contemporary Dance Category                2874
Ensembles                                   451
Special Awards                              446
Large Ensembles                             133
Pas De Deux                                  73
Small Ensembles                              67
Classical & Contemporary Dance Category      24
Duets & Trios                                 3
Name: count, dtype: int64

In [11]:
# for i in winners["Division / Position"].value_counts().index:
#     print(i)

In [12]:
winners["Division / Position"] = winners["Division / Position"].str.replace(r"\(.*\)", "", regex=True).str.strip()
winners["Division / Position"].value_counts()

Division / Position
Junior Age Division             11795
Senior Age Division             11604
Pre-Competitive Age Division     7446
Large Ensembles                   368
Small Ensembles                   358
Pas De Deux                       293
Ensembles                         130
Special Awards                    120
Duet/Trio                          16
Name: count, dtype: int64

In [13]:
winners[winners.Name.str.contains(",", na=False)][["Name", "Category", "Division / Position"]]

,Name,Category,Division / Position
6,"Kory Glatman, NJ",NaN,NaN
87,"Melissa Lorry, MA",Contemporary Dance Category,NaN
124,"Arizona Ballet School, AZ",Special Awards,NaN
186,"April Rae, MD",NaN,NaN
207,"Bills, Bills, Bills",Large Ensembles,NaN
...,...,...,...
41363,"Strong, Calm, Slow",NaN,Duet/Trio
41910,"Diana & Acteon , Pas De Deux",NaN,Small Ensembles
41912,"Diana & Acteon , Pas De Deux",NaN,Small Ensembles
43165,"Spin, Measure, Cut",NaN,Small Ensembles
43180,"Spin, Measure, Cut",NaN,Small Ensembles

In [14]:
winners.loc[
    winners["Dance Category"].str.contains("Ensembles And Pas De Deux", na=False), 
    "Dance Category" 
] = "Ensembles & Pas De Deux"

winners.loc[
    winners["Dance Category"].str.contains(r"\bDuet\b|\bTrio\b", na=False), 
    "Dance Category"
] = "Duet/Trio"

In [15]:
winners["Dance Category"].value_counts()

Dance Category
Classical Dance Category                   17361
Contemporary Dance Category                11612
Ensembles                                   1793
Special Awards                               889
Pas De Deux                                  477
Large Ensembles                              198
Small Ensembles                              110
Classical & Contemporary Dance Category      104
Ensembles & Pas De Deux                       47
Duets & Pas De Deux                           28
Contemporary/Open Dance Category              17
Top 12                                        15
Duet/Trio                                     11
Traditional Dance Category                     9
Top 6                                          6
Name: count, dtype: int64

In [16]:
winners.isna().sum()

Name                     554
School                 36132
Year                       0
City                       0
Award                    174
Division               36913
Category               36477
School / Company        8286
Division / Position    11327
Dance Category         10780
dtype: int64

- Some awards are for the school overall rather than a person
- Some awards are for the name of the dance rather than people
- School awards wouldn't have a Dance Category or Position, which would explain some entries being null
- NaNs in certain columns can actually tell you what kind of award is being given:
    - NaN in School/Company ; School Award
- Some people don't belong in a School/Company

# Data Cleanup:

- Whenever Name and School have NaNs, there are no rows where School/Company is empty
    - So: replace School with whatever is in the School/Company for that row
    - vice versa if School/Company is empty but School isn't empty

In [17]:
winners[
    (winners.Name.isna()) & 
    (winners.School.isna())
]

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
7717,NaN,NaN,2011,"Torrington, CT",Outstanding School Award,NaN,NaN,"Washington School of Ballet, DC, USA",NaN,Special Awards
7806,NaN,NaN,2011,"Tampa, FL",Outstanding School Award,NaN,NaN,The Art of Classical Ballet,NaN,Special Awards
7807,NaN,NaN,2011,"Tampa, FL",Outstanding School Award,NaN,NaN,America's Ballet School,NaN,Special Awards
7905,NaN,NaN,2011,"San Francisco, CA",Outstanding School Award,NaN,NaN,"Los Angeles Ballet Academy, CA",NaN,Special Awards
7906,NaN,NaN,2011,"San Francisco, CA",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",NaN,Special Awards
...,...,...,...,...,...,...,...,...,...,...
42644,NaN,NaN,2026,"Boca Raton, FL",Outstanding School Award,NaN,NaN,"Stars Dance Studio, FL",Special Awards,NaN
42928,NaN,NaN,2026,"Indianapolis, IN",Outstanding School Award,NaN,NaN,"Indiana Ballet Conservatory, IN",Special Awards,NaN
43200,NaN,NaN,2026,"Boston-Worcester, MA",Outstanding School Award,NaN,NaN,"N&D Ballet, MA",Special Awards,NaN
43201,NaN,NaN,2026,"Boston-Worcester, MA",Outstanding School Award,NaN,NaN,"Koltun Ballet Boston, MA",Special Awards,NaN
43456,NaN,NaN,2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

In [18]:
winners[
    (winners.Name.isna()) & 
    (winners.School.isna()) &
    (winners["School / Company"].isna())
]

Empty DataFrame
Columns: [Name, School, Year, City, Award, Division, Category, School / Company, Division / Position, Dance Category]
Index: []

In [19]:
mask = (winners["Name"].isna()) & (winners["School"].isna())

winners.loc[mask, "School"] = winners.loc[mask, "School / Company"]
winners

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
0,NaN,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
1,NaN,"The Kirov Academy, DC",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
2,8+3,Inwood Dance Company,2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
3,Cabaret,"Dance Conservatory, DE",2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
4,Make Them Hear You,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",2nd Place,NaN,Ensembles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
43452,Dance For Six,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43453,Coppelia Friends Dance,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
43454,Kira Fargas,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43455,Hadassah Perry,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
43456,NaN,"Westlake School for the Performing Arts, CA",2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

In [20]:
mask =  (winners.School.isna()) & (~winners["School / Company"].isna())
winners.loc[
    mask,
    "School"    
] = winners.loc[mask, "School / Company"]

In [21]:
mask = (~winners.School.isna()) & (winners["School / Company"].isna())
winners.loc[
    mask,
    "School / Company"
] = winners.loc[mask, "School"]

In [22]:
winners.isna().sum()

Name                     554
School                   961
Year                       0
City                       0
Award                    174
Division               36913
Category               36477
School / Company         961
Division / Position    11327
Dance Category         10780
dtype: int64

- Removing hanging whitespace from all string columns since it will effect analysis
- Turn everything uppercase, since there are inconsistent capitalization (or lack thereof)

In [23]:
winners["Name"] = winners.Name.str.strip()

In [24]:
str_cols = winners.select_dtypes(include=["object", "string"]).columns

for col in str_cols:
    mask = winners[col].notna()
    winners.loc[mask, col] = (
        winners.loc[mask, col]
        .astype(str)
        .str.replace(r"\s+,", ",", regex=True)
        .str.replace(r",\s+,", ",", regex=True)
        .str.replace(r"\(\s+(\d+)", r"(\1", regex=True)
        .str.replace(r"(\d+)\s+\)", r"\1)", regex=True)
    )

In [25]:
winners = winners.apply(lambda col: col.str.upper() if col.dtype == "object" else col)

In [26]:
names = sorted(winners.Name.dropna().unique())

with open("data/yagp_names.txt", "w") as file:
    file.writelines(
        name + "\n" for name in names
    )

In [27]:
# winners[winners.Name.str.contains("&", na=False)]

In [28]:
# winners[winners.Name.str.contains("& &", na=False)]

In [29]:
# winners[winners.Name.str.contains(r"\bAND\b", na=False)]

- & and "AND" separates names, but some rows have one too many & with whitespace in the middle (& &) 
    - some dances have "AND" in them too :(
        - So replace "&", "& &", and " AND" with a comma (space between name/dance to deal with whitespace)
        - Don't .str.split() on commas just yet, since dances also have commas (need to distinguish what has dancer names and what are names of dances)
- Removing ages and other dances in parentheses, but there's sometimes a hanging comma (ends in comma)

In [30]:
def split_names(string):
    if pd.isna(string):
        return string  # keep NaN
    
    if isinstance(string, str):
        return [s.strip() for s in string.split("&")]
    
    return string

winners.Name = winners.Name.str.replace(r"& &", "&")
winners.Name = winners.Name.apply(split_names)
winners = winners.explode("Name", ignore_index=True)

In [31]:
winners["Name"] = winners.Name.str.replace(r"\(.*\)", "", regex=True).str.strip()

In [32]:
winners["Names_resolved"] = winners.Name.str.replace(r" \bAND\b", ",").str.strip()
winners["Names_resolved"] = winners.Names_resolved.str.replace(r"\(.*\)", "", regex=True).str.strip()
winners["Names_resolved"] = winners.Names_resolved.str.replace(r",$", "", regex=True).str.strip()

In [33]:
winners["Names_resolved"] = winners["Names_resolved"].str.split(",")

winners[~winners.Names_resolved.isna()]

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category,Names_resolved
2,8+3,INWOOD DANCE COMPANY,2000,"WASHINGTON, DC",3RD PLACE (TIE),NaN,ENSEMBLES,INWOOD DANCE COMPANY,NaN,NaN,[8+3]
3,CABARET,"DANCE CONSERVATORY, DE",2000,"WASHINGTON, DC",3RD PLACE (TIE),NaN,ENSEMBLES,"DANCE CONSERVATORY, DE",NaN,NaN,[CABARET]
4,MAKE THEM HEAR YOU,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",2ND PLACE,NaN,ENSEMBLES,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,[MAKE THEM HEAR YOU]
5,CAPRICE,"DANCE CONSERVATORY, DE",2000,"WASHINGTON, DC",1ST PLACE,NaN,ENSEMBLES,"DANCE CONSERVATORY, DE",NaN,NaN,[CAPRICE]
6,"KORY GLATMAN, NJ",NaN,2000,"WASHINGTON, DC",3RD PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,"[KORY GLATMAN, NJ]"
...,...,...,...,...,...,...,...,...,...,...,...
43515,GERDA'S RIVER JOURNEY,"BAYER BALLET ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"BAYER BALLET ACADEMY, CA",LARGE ENSEMBLES,NaN,[GERDA'S RIVER JOURNEY]
43516,DANCE FOR SIX,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",LARGE ENSEMBLES,NaN,[DANCE FOR SIX]
43517,COPPELIA FRIENDS DANCE,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"WESTLAKE SCHOOL FOR THE PERFORMING ARTS, CA",LARGE ENSEMBLES,NaN,[COPPELIA FRIENDS DANCE]
43518,KIRA FARGAS,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,[KIRA FARGAS]
43519,HADASSAH PERRY,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,[HADASSAH PERRY]

In [34]:
names = winners[winners.Name.str.contains(",", na=False) == False].Name.unique()

winners.loc[
    ((winners.Names_resolved.str[1].str.strip() + " " + winners.Names_resolved.str[0].str.strip()).isin(names)), 
    ["Names_resolved"]
] = winners.Names_resolved.str[1].str.strip() + " " + winners.Names_resolved.str[0].str.strip()

winners.loc[
    ((winners.Names_resolved.str[0].str.strip() + " " + winners.Names_resolved.str[1].str.strip()).isin(names)), 
    ["Names_resolved"]
] = winners.Names_resolved.str[0].str.strip() + " " + winners.Names_resolved.str[1].str.strip()

In [35]:
yt = winners.Names_resolved.explode()
yt[~yt.isna()]

6                 KORY GLATMAN
6                           NJ
87               MELISSA LORRY
87                          MA
124      ARIZONA BALLET SCHOOL
                 ...
43229                  MEASURE
43229                      CUT
43244                     SPIN
43244                  MEASURE
43244                      CUT
Name: Names_resolved, Length: 583, dtype: object

- US state abbreviations followed after names need to be removed
- ages not in parentheses need to be removed

In [36]:
patterns = re.compile(
    r"^(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC|\d{1,2})$"
)

# def remove_state_age(x):
#     if isinstance(x, list) and len(x) == 2:
#         first, second = x
#         if isinstance(second, str) and patterns.fullmatch(second.strip()):
#             return first.strip()
        
#     if isinstance(x, list) and len(x) == 4:
#         first, second, third, fourth = x
#         if second.strip().isdigit() & fourth.strip().isdigit():
#             return [first.strip(), third.strip()]
#     return x

def remove_state_age(x):
    if not isinstance(x, list):
        return x
    
    cleaned = []
    for i in x:
        i = i.strip()
        if patterns.fullmatch(i):
            continue
        cleaned.append(i)

    return cleaned

winners["Names_resolved"] = winners["Names_resolved"].apply(remove_state_age)

In [37]:
for i in winners.Names_resolved[~winners.Names_resolved.isna()].value_counts().index:
    if not isinstance(i, list):
        print(i)

COPPELIA PAS DE DEUX
DON QUIXOTE PAS DE DEUX
ALEXANDRIA MARX
RACHEL ROHRICH
HARLEQUINADE PAS DE DEUX
SILVI LYBBERT
JESLYN CHEN
SWAN LAKE PAS DE TROIS
ORLANDO BALLET SCHOOL FL
MASUMI YOSHIMOTO
PAS DE DEUX GRAND PAS CLASSIQUE
ODALISQUES LE CORSAIRE
RYLAND ACREE III
LAUREN LEB
GENEVIEVE COOVREY
JASMINE JIMISON
ALL AMERICAN CLASSICAL BALLET SCHOOL FL

# Dancers:
- classifications: person, people

In [38]:
dancers = winners.dropna(subset="Name")
dancers.shape

(42966, 11)

## Finding a column to filter people/person from:

- Category:
    - ENSEMBLES ; DANCES
    - LARGE ENSEMBLES ; DANCES
    - PAS DE DEUX ; DANCES AND NAMES
    - SMALL ENSEMBLES ; DANCES
    - DUETS & TRIOS ; DANCES

In [39]:
# sorted(dancers[dancers["Category"].str.contains(r"PAS DE DEUX", na=False)].Name.unique())

In [40]:
dances = list(dancers[dancers["Category"].str.contains(r"ENSEMBLES|LARGE ENSEMBLES|SMALL ENSEMBLES|DUETS & TRIOS", na=False)].Name)

- Division / Position:
    - LARGE ENSEMBLES ; DANCES
    - SMALL ENSEMBLES ; DANCES AND NAMES
    - PAS DE DEUX ; DANCES AND NAMES
    - ENSEMBLES ; DANCES AND NAMES
    - DUET/TRIO ; DANCES

In [41]:
# sorted(dancers[dancers["Division / Position"].str.contains(r"SMALL ENSEMBLES", na=False)].Name.unique())

In [42]:
# sorted(dancers[dancers["Division / Position"].str.contains(r"PAS DE DEUX", na=False)].Name.unique())

In [43]:
# sorted(dancers[dancers["Division / Position"].str.contains(r"ENSEMBLES", na=False)].Name.unique())

In [44]:
dances += list(dancers[dancers["Division / Position"].str.contains(r"LARGE ENSEMBLES|DUET/TRIO", na=False)].Name)

- Dance Category:
    - ENSEMBLES ; MOSTLY DANCES AND NAMES
    - PAS DE DEUX ; DANCES AND NAMES
    - LARGE ENSEMBLES ; DANCES
    - SMALL ENSEMBLES ; DANCES
    - ENSEMBLES & PAS DE DEUX ; MOSTLY NAMES (KOREAN DANCERS) AND SOME DANCES
    - DUETS & PAS DE DEUX ; DANCES
    - DUET/TRIO ; DANCES

In [45]:
# sorted(dancers[dancers["Dance Category"].str.contains("ENSEMBLES", na=False)].Name.unique())

In [46]:
# sorted(dancers[dancers["Dance Category"].str.contains("PAS DE DEUX", na=False)].Name.unique())

In [47]:
d = dancers[dancers["Dance Category"].str.contains("ENSEMBLES & PAS DE DEUX", na=False)].Name.unique()
print(d)

dance_pattern = re.compile(r'^[^가-힣]+$') # keep anything that does NOT contain Korean characters
d = [x for x in d if dance_pattern.match(x)]

dances += d
d

['JIOH KIM 김지오' 'SIWOO JEONG 정시우' 'YUNJIN BAE 배윤진' 'JUMYEONG JANG 장주명'
 'JAEMYEONG JANG 장재명' 'SUNGYEON HONG 홍성연' 'SHIJEAN KIM 김시진'
 'SEOHYUN KIM 김서현' 'SEOYEON JEONG 정서연' 'GINA CHOI 최기나' 'NURI PARK 박누리'
 'SIHU BAN 반시후' 'HYEWON KANG 강혜원' 'SUNGMIN KIM 김성민' 'DOEUN KIM 김도은'
 'NAYEON KIM 김나연' 'BOYOUNG KIM 김보영' 'JIHYEONG CHOI 최지형' 'JIYOUNG KIM 김지영'
 'JIYU KWON 권지유' 'ALL ENSEMBLES' 'NOWHERE TOGETHER' 'WHISPER IN MY EAR']

['ALL ENSEMBLES', 'NOWHERE TOGETHER', 'WHISPER IN MY EAR']

In [48]:
dances += list(dancers[dancers["Dance Category"].str.contains(r"LARGE ENSEMBLES|SMALL ENSEMBLES|DUETS & PAS DE DEUX|DUET/TRIO", na=False)].Name)

In [49]:
dances = np.sort(np.unique(dances))

# Final Dancers data:

In [50]:
dancers = dancers[
    (~dancers.Name.isin(dances))
]

dancers

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category,Names_resolved
6,"KORY GLATMAN, NJ",NaN,2000,"WASHINGTON, DC",3RD PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,[KORY GLATMAN]
7,ASHTON BERKLEY,"THE KIROV ACADEMY, DC",2000,"WASHINGTON, DC",2ND PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,"THE KIROV ACADEMY, DC",NaN,NaN,NaN
8,DANA GAULE,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",1ST PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,NaN
9,KATRINA DALTON,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",HOPE AWARD,PRE-COMPETITIVE AGE DIVISION,NaN,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,NaN
10,TIFFANY SMITH,"HARRISBUG DANCE CONSERVATORY, PA",2000,"WASHINGTON, DC",3RD PLACE (TIE),JUNIOR AGE DIVISION,CONTEMPORARY DANCE CATEGORY,"HARRISBUG DANCE CONSERVATORY, PA",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
43499,THE LAKE,"THE DANCE CENTER (TDC), CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"THE DANCE CENTER (TDC), CA",SMALL ENSEMBLES,NaN,NaN
43500,THE ORBITS,"EVA DANCE ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"EVA DANCE ACADEMY, CA",SMALL ENSEMBLES,NaN,NaN
43501,WITHOUT YOU,"JUN LU PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"JUN LU PERFORMING ARTS, CA",SMALL ENSEMBLES,NaN,NaN
43518,KIRA FARGAS,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN
43519,HADASSAH PERRY,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN

In [51]:
dancers["classification"] = dancers.apply(classify_name, axis=1)

In [52]:
dancers[["Name", "classification"]]

                   Name classification
6      KORY GLATMAN, NJ         person
7        ASHTON BERKLEY         person
8            DANA GAULE         person
9        KATRINA DALTON         person
10        TIFFANY SMITH         person
...                 ...            ...
43499          THE LAKE          dance
43500        THE ORBITS          dance
43501       WITHOUT YOU          dance
43518       KIRA FARGAS         person
43519    HADASSAH PERRY         person

[41188 rows x 2 columns]

In [53]:
dancers.classification.value_counts()

classification
person          39028
dance            2143
unknown            13
school              2
multi_person        2
Name: count, dtype: int64

In [54]:
dancers = dancers[dancers.classification.str.contains(r"person|multi_person")]
dancers

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category,Names_resolved,classification
6,"KORY GLATMAN, NJ",NaN,2000,"WASHINGTON, DC",3RD PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,[KORY GLATMAN],person
7,ASHTON BERKLEY,"THE KIROV ACADEMY, DC",2000,"WASHINGTON, DC",2ND PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,"THE KIROV ACADEMY, DC",NaN,NaN,NaN,person
8,DANA GAULE,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",1ST PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,NaN,person
9,KATRINA DALTON,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",HOPE AWARD,PRE-COMPETITIVE AGE DIVISION,NaN,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,NaN,person
10,TIFFANY SMITH,"HARRISBUG DANCE CONSERVATORY, PA",2000,"WASHINGTON, DC",3RD PLACE (TIE),JUNIOR AGE DIVISION,CONTEMPORARY DANCE CATEGORY,"HARRISBUG DANCE CONSERVATORY, PA",NaN,NaN,NaN,person
...,...,...,...,...,...,...,...,...,...,...,...,...
43480,SOFIA ALIYEV,"BAYER BALLET ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"BAYER BALLET ACADEMY, CA",PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,person
43481,YILING LI,"BAYER BALLET ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"BAYER BALLET ACADEMY, CA",PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,person
43482,ZUOYI DU,"ACADEMY OF PALO ALTO PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"ACADEMY OF PALO ALTO PERFORMING ARTS, CA",PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,person
43518,KIRA FARGAS,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN,person
43519,HADASSAH PERRY,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN,person

In [55]:
dancers = dancers.explode(column="Names_resolved")

- Misspellings/errors:
    - ALANAGRIFFITH = ALANA GRIFFITH
    - ALTHEA JOHNSON - STAUB
    - ANDREAJONUSAS = ANDREA JONUSAS
    - ELISA D[CARPIO = ELISA D'CARPIO
    - GABRIELLEGIRARD = GABRIELLE GIRARD
    - LOGANHILLMAN = LOGAN HILLMAN
    - MAKAI LEWIS - REES
    - MARIARODRIGUEZ = MARIA RODRIGUEZ
    - PHILIP MARTIN‐NIELSON
    - SHERY MORAY = SHERRY MORAY
    - SHI HANY HUANG = SHI HANG HUANG
    - VICTORIAHASK = VICTORIA HASK
    - WING YAN [IBBY] CHOW
- Names containing commas that need to be fixed:
    - 'CAROLIE, LAUVETZ'
    - 'ALESSANDRO FROLA, 12, MARTINA MANTOVANI, 13'
    - 'VALENTINA LEALI, MASSIMO SONZOGNI'
    - 'NORA CLEMENTE, 16, BRYCE LEE, 16'
    - 'WATMORA CASEY, TATYANA MAZUR'
    - 'JESSICA ODASZ, ANDREA ASTUTO'
    - 'KATIA GARZA, TODD ERIC ALLEN'
    - 'NADIA, TENCER'
- Different Names for the same person:
    - CHEN LI-EN, LIESL = LI-EN, LIESL CHEN ; LIESL CHEN
    - GOH JIA YI, ANU = GOH JIA YI
    - KENNETH SHELBY, JR = KENNETH DUANE SHELBY, JR ; KENNETH DUANE SHELBY JR
    - NADIA VESELOVA TENCER = NADIA VESELOVA-TENCER = NADIA, TENCER ; NADIA VESELOVA-TENCER
    - PHYLICIA, ZI YING CHEW = ZI YING CHEW
    - SOFIA, ZI XUAN LEE = ZI XUAN LEE

- Inconsistent patterns for recording names:
    - First Name Last Name(s)
    - Last Name, First Name
    - First Name Last Name, [US state]
    - First Name Middle Name(s) and Last Name(s)
    - [1st person] & [2nd person]
    - [1st person], [2nd person]
    - [1st person] (age), [2nd person] (age)
    - (age)
    - [1st person] age, [2nd person] age (where age isn't in parentheses)
    - First Name Last Name (age), (dance that the person/people performed)
    - dance that the person/people performed, ([1st person], [2nd person])

In [56]:
winners.loc[
    winners.Name.str.contains("ABIGAIL, BOIVIN", na=False),
    "Name"
] = "ABIGAIL BOIVIN"

winners.loc[
    winners.Name.str.contains("ALANAGRIFFITH", na=False),
    "Name"
] = "ALANA GRIFFITH"

winners.loc[
    winners.Name.str.contains("ANDREAJONUSAS", na=False),
    "Name"
] = "ANDREA JONUSAS"

winners.loc[
    winners.Name.str.contains("BRITTANY, GEORGHEGAN", na=False),
    "Name"
] = "BRITTANY GEORGHEGAN"

winners.loc[
    winners.Name.str.contains("CAROLIE, LAUVETZ", na=False),
    "Name"
] = "CAROLIE LAUVETZ"

winners.loc[
    winners.Name.str.contains("ELISA D[CARPIO", regex=False, na=False),
    "Name"
] = "ELISA D'CARPIO"

winners.loc[
    winners.Name.str.contains("GABRIELLEGIRARD", na=False),
    "Name"
] = "GABRIELLE GIRARD"

winners.loc[
    winners.Name.str.contains("GOH JIA YI, ANU", na=False),
    "Name"
] = "GOH JIA YI"

winners.loc[
    (winners.Name.str.contains("KENNETH SHELBY, JR", na=False)) |
    (winners.Name.str.contains("KENNETH DUANE SHELBY, JR", na=False)),
    "Name",
] = "KENNETH DUANE SHELBY JR"

winners.loc[
    (winners.Name.str.contains("CHEN LI-EN, LIESL", na=False)) |
    (winners.Name.str.contains("LI-EN, LIESL CHEN", na=False)),
    "Name",
] = "LIESL CHEN"

winners.loc[
    winners.Name.str.contains("LOGANHILLMAN", na=False),
    "Name"
] = "LOGAN HILLMAN"

winners.loc[
    winners.Name.str.contains("MARIARODRIGUEZ", na=False),
    "Name"
] = "MARIA RODRIGUEZ"

# winners.loc[
#     (winners.Name.str.contains("NADIA VESELOVA TENCER", na=False)) |
#     (winners.Name.str.contains("NADIA VESELOVA-TENCER", na=False)) |
#     (winners.Name.str.contains("NADIA, TENCER", na=False)),
#     "Name",
# ] = "NADIA VESELOVA-TENCER"

winners.loc[
    winners.Name.str.contains("TAYLOR, HOGAN", na=False),
    "Name"
] = "TAYLOR HOGAN"

winners.loc[
    winners.Name.str.contains("TORI, JENNINGS", na=False),
    "Name"
] = "TORI JENNINGS"

winners.loc[
    winners.Name.str.contains("VICTORIAHASK", na=False),
    "Name"
] = "VICTORIA HASK"

winners.loc[
    winners.Name.str.contains("SOFIA, ZI XUAN LEE", na=False),
    "Name"
] = "ZI XUAN LEE"

winners.loc[
    winners.Name.str.contains("PHYLICIA, ZI YING CHEW", na=False),
    "Name"
] = "ZI YING CHEW"

# winners.loc[
#     winners.Name.str.contains("SHERY MORAY", na=False),
#     "Name"
# ] = "SHERRY MORAY"

# winners.loc[
#     winners.Name.str.contains("SHI HANY HUANG", na=False),
#     "Name"
# ] = "SHI HANG HUANG"

# winners.loc[
#     winners.Name.str.contains("ANA LUIZA ARANTES NEGRAO", na=False),
#     "Name"
# ] = "ANA LUISA ARANTES NEGRAO"

# winners.loc[
#     winners.Name.str.contains("AMYRA CRISTIN BADRO", na=False),
#     "Name"
# ] = "AMYRA CRISTINA BADRO"

In [57]:
def last_token(name):
    return name.split()[-1] if isinstance(name, str) and name.split() else ""


def first_token(name):
    return name.split()[0] if isinstance(name, str) and name.split() else ""


unique_names = sorted(dancers["Name"].dropna().unique())

threshold = 90
canonical_map = {}
visited = set()

for name in unique_names:
    if name in visited:
        continue

    matches = process.extract(
        name,
        unique_names,
        scorer=fuzz.token_sort_ratio,
        limit=None
    )

    group = []
    for candidate, score, _ in matches:
        if score < threshold:
            continue

        # avoid bad merges:
        # require same first OR same last token
        if first_token(candidate) == first_token(name) or last_token(candidate) == last_token(name):
            group.append(candidate)

    # choose canonical:
    # prefer most common name in dataset, then shortest
    counts = dancers["Names_resolved"].value_counts()

    canonical = sorted(
        group,
        key=lambda x: (-counts.get(x, 0), len(x), x)
    )[0]

    for g in group:
        canonical_map[g] = canonical
        visited.add(g)

dancers["Name_canonical"] = dancers["Names_resolved"].map(canonical_map)

In [58]:
groups = {}

for original, canonical in canonical_map.items():
    groups.setdefault(canonical, []).append(original)

merge_review = {
    k: sorted(v)
    for k, v in groups.items()
    if len(v) > 1
}

# len(merge_review), merge_review

In [59]:
merge_review_df = pd.DataFrame([
    {"canonical": k, "variants": v, "n_variants": len(v)}
    for k, v in merge_review.items()
]).sort_values("n_variants", ascending=False)

merge_review_df.sort_values("canonical", inplace=True)
merge_review_df

,canonical,variants,n_variants
1,ABGAIL KURDIN,"[ABGAIL KURDIN, ABIGAIL KURDIN]",2
3,ABIGAIL GROSS,"[ABIGAIL GROSS, ABIGAIL ROSAS]",2
4,ABIGAIL HAU,"[ABIGAIL HAU, ABIGAIL LAU]",2
5,ABIGAIL JACKSON,"[ABIGAIL JACKSON, ABIGIAL JACKSON]",2
6,ABIGAIL MATHEWS,"[ABIGAIL MATHEWS, ABIGAIL MATTHEWS]",2
...,...,...,...
670,YUKINA CHIBA,"[YUKINA CHIBA, YUKINO CHIBA]",2
671,ZAK SCHLEGEL,"[ZAK SCHELEGEL, ZAK SCHLEGEL]",2
672,ZALOA FABBRINI,"[ZALOA FABBRINI, ZALOA FABRINNI]",2
673,ZIMMI MARIE COKER,"[ZIMMI MARIE COCKER, ZIMMI MARIE COKER]",2
674,ZOE ACOSTA BROWN DEAL,"[ZOE ACOSTA BROWN DEAL, ZOË ACOSTA-BROWN DEAL]",2

In [60]:
dancers.isna().sum()

Name                       0
School                   925
Year                       0
City                       0
Award                    146
Division               32518
Category               32910
School / Company         925
Division / Position     7866
Dance Category          9085
Names_resolved         38978
classification             0
Name_canonical         39034
dtype: int64

In [61]:
dancers.loc[
    (~dancers.Names_resolved.isna()), 
    "Name"]= dancers.loc[(~dancers.Names_resolved.isna()), "Names_resolved"]

In [62]:
dancers

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category,Names_resolved,classification,Name_canonical
6,KORY GLATMAN,NaN,2000,"WASHINGTON, DC",3RD PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,NaN,NaN,NaN,KORY GLATMAN,person,NaN
7,ASHTON BERKLEY,"THE KIROV ACADEMY, DC",2000,"WASHINGTON, DC",2ND PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,"THE KIROV ACADEMY, DC",NaN,NaN,NaN,person,NaN
8,DANA GAULE,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",1ST PLACE,PRE-COMPETITIVE AGE DIVISION,NaN,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,NaN,person,NaN
9,KATRINA DALTON,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",2000,"WASHINGTON, DC",HOPE AWARD,PRE-COMPETITIVE AGE DIVISION,NaN,"ALLEGRO DANCE ARTS ACADEMY, NJ, USA",NaN,NaN,NaN,person,NaN
10,TIFFANY SMITH,"HARRISBUG DANCE CONSERVATORY, PA",2000,"WASHINGTON, DC",3RD PLACE (TIE),JUNIOR AGE DIVISION,CONTEMPORARY DANCE CATEGORY,"HARRISBUG DANCE CONSERVATORY, PA",NaN,NaN,NaN,person,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43480,SOFIA ALIYEV,"BAYER BALLET ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"BAYER BALLET ACADEMY, CA",PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,person,NaN
43481,YILING LI,"BAYER BALLET ACADEMY, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"BAYER BALLET ACADEMY, CA",PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,person,NaN
43482,ZUOYI DU,"ACADEMY OF PALO ALTO PERFORMING ARTS, CA",2026,"SAN FRANCISCO, CA (MAR)",TOP 12,NaN,NaN,"ACADEMY OF PALO ALTO PERFORMING ARTS, CA",PRE-COMPETITIVE AGE DIVISION,CONTEMPORARY DANCE CATEGORY,NaN,person,NaN
43518,KIRA FARGAS,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN,person,NaN
43519,HADASSAH PERRY,FOR ALL THE WORK,2026,"SAN FRANCISCO, CA (MAR)",OUTSTANDING CHOREOGRAPHER AWARD,NaN,NaN,FOR ALL THE WORK,SPECIAL AWARDS,NaN,NaN,person,NaN

In [63]:
"(FLAMES OF PARIS"

'(FLAMES OF PARIS'