# Imports and data:

In [1]:
import pandas as pd
import altair as alt

In [2]:
w1 = pd.read_excel("data/WINNERS 2000-2010 - 05.xlsx")
w2 = pd.read_excel("data/WINNERS 2011-2020 - 05.xlsx")
w3 = pd.read_excel("data/WINNERS 2021-2025 - 05.xlsx")
w4 = pd.read_excel("data/WINNERS 2026-2030 - 05.xlsx")

In [3]:
winners = pd.concat([w1, w2, w3, w4])

winners.shape

(43457, 10)

In [4]:
winners

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
0,NaN,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
1,NaN,"The Kirov Academy, DC",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
2,8+3,Inwood Dance Company,2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
3,Cabaret,"Dance Conservatory, DE",2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
4,Make Them Hear You,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",2nd Place,NaN,Ensembles,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
8296,Dance For Six,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
8297,Coppelia Friends Dance,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
8298,Kira Fargas,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
8299,Hadassah Perry,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
8300,NaN,NaN,2026,"San Francisco, CA (Mar)",Outstanding School Award,NaN,NaN,"Westlake School for the Performing Arts, CA",Special Awards,NaN

# Data Cleanup:

In [5]:
winners.isna().sum()

Name                     554
School                 36132
Year                       0
City                       0
Award                    174
Division               36913
Category               36477
School / Company        8286
Division / Position    11327
Dance Category         10780
dtype: int64

- Some awards are for the school overall rather than a person
- School awards wouldn't have a Dance Category or Position, which would explain some entries being null
- NaNs in certain columns can actually tell you what kind of award is being given:
    - NaN in School/Company ; School Award
- Some people don't belong in a School/Company

In [6]:
school_awards = winners[
    (winners.Name.isna()) & 
    (winners.School.isna() == False)
]

school_awards

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
0,NaN,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
1,NaN,"The Kirov Academy, DC",2000,"Washington, DC",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
24,NaN,"School of International Ballet, CA",2000,"Long Beach, CA",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
28,NaN,"Ayako School of Ballet, CA, USA",2000,"Long Beach, CA",Outstanding Choreographer Award,NaN,Special Awards,NaN,NaN,NaN
74,NaN,"Robin Horneff Performing Arts Center, NJ",2000,"Boston, MA",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7195,NaN,Los Angeles Ballet Academy,2010,"Los Angeles, CA",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
7315,NaN,"Classical Ballet Academy, UT",2010,"Denver, CO",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
7401,NaN,"Ballet Academy of Texas, TX, USA",2010,"Dallas, TX",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
7596,NaN,"Joffrey Academy of Dance, Official School of t...",2010,"Chicago, IL",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN
7597,NaN,"Russian Ballet Academy of Indiana, IN",2010,"Chicago, IL",Outstanding School Award,NaN,Special Awards,NaN,NaN,NaN

In [7]:
dancer_awards = winners[
    (winners.Name.isna() == False)
]

dancer_awards

,Name,School,Year,City,Award,Division,Category,School / Company,Division / Position,Dance Category
2,8+3,Inwood Dance Company,2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
3,Cabaret,"Dance Conservatory, DE",2000,"Washington, DC",3rd Place (tie),NaN,Ensembles,NaN,NaN,NaN
4,Make Them Hear You,"Allegro Dance Arts Academy, NJ, USA",2000,"Washington, DC",2nd Place,NaN,Ensembles,NaN,NaN,NaN
5,Caprice,"Dance Conservatory, DE",2000,"Washington, DC",1st Place,NaN,Ensembles,NaN,NaN,NaN
6,"Kory Glatman, NJ",NaN,2000,"Washington, DC",3rd Place,Pre-Competitive Age Division,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
8295,Gerda'S River Journey,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Bayer Ballet Academy, CA",Large Ensembles,NaN
8296,Dance For Six,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
8297,Coppelia Friends Dance,NaN,2026,"San Francisco, CA (Mar)",Top 12,NaN,NaN,"Westlake School for the Performing Arts, CA",Large Ensembles,NaN
8298,Kira Fargas,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN
8299,Hadassah Perry,NaN,2026,"San Francisco, CA (Mar)",Outstanding Choreographer Award,NaN,NaN,For All The Work,Special Awards,NaN

# Interesting Aggregates:

In [8]:
winners.Name.value_counts()

Name
Faculty               43
Caitlyn Dioneda       36
Katia Almayeva        33
Aurora Kellogg        30
Nicole Denney         28
                      ..
Fabi Calborn           1
Stacey Aung            1
Katie Sherman          1
Chloe Felesina         1
Michelle Carpenter     1
Name: count, Length: 16831, dtype: int64

In [9]:
winners.School.value_counts()

School
Southland Ballet Academy                     132
Ballet Academy of Texas, TX, USA             112
International Ballet School, CO               91
Orlando Ballet School                         85
The Rock School for Dance Education, PA       83
                                            ...
European Dance Studio, NC                      1
School of Dance Petite Danse                   1
Harrisbug Dance Conservatory, PA               1
Escuela Superior de Ballet de Guadalajara      1
Deane Dance Center, CA                         1
Name: count, Length: 1790, dtype: int64

In [10]:
winners.groupby(["School", "Award"])["Year"].count()

School                               Award
1 Dance Academy                      Top 12                      1
A Touch of Class Performing Arts.    Top 12                      1
AIS Ballet JAPAN, JAPAN              Top 12                      1
AS Ballet Schulle Boll, SWITZERLAND  Top 12                      1
AS Balletschule, SWITZERLAND         1st Place                   1
                                                                ..
ktm eXtremes Dance Project           1st Place                   1
                                     2nd Place                   1
                                     Outstanding School Award    1
ktm eXtremes dance project           2nd Place                   1
                                     Top 12                      2
Name: Year, Length: 3395, dtype: int64

In [11]:
winners.groupby(["School", "Award", "Year"])[["Year"]].count()

                                                                   Year
School                              Award                    Year
1 Dance Academy                     Top 12                   2002     1
A Touch of Class Performing Arts.   Top 12                   2008     1
AIS Ballet JAPAN, JAPAN             Top 12                   2009     1
AS Ballet Schulle Boll, SWITZERLAND Top 12                   2009     1
AS Balletschule, SWITZERLAND        1st Place                2010     1
...                                                                 ...
ktm eXtremes Dance Project          2nd Place                2004     1
                                    Outstanding School Award 2004     1
ktm eXtremes dance project          2nd Place                2004     1
                                    Top 12                   2004     1
                                                             2005     1

[4197 rows x 1 columns]